Repository dasch-swiss/dsp-das, pull requests merged in 2019-06, with the labels that each got.

#18 fix(yarn): fix vulnerability with js-yaml and handlebars
  yarn.lock
Labels: bug

#16 feat(admin): Show and set system admin
  src/app/system/users/users-list/users-list.component.html
  src/app/system/users/users-list/users-list.component.ts
  src/app/system/users/users.component.ts
Labels: enhancement

#21 Feat: Open project from landing-page
  src/app/app-routing.module.ts
  src/app/main/grid/grid.component.html
  src/app/main/grid/grid.component.scss
  src/app/main/grid/grid.component.spec.ts
  src/app/main/grid/grid.component.ts
  src/app/main/main.component.ts
  src/app/project/board/board.component.ts
  src/app/project/project.component.ts
  yalc.lock
Labels: enhancement

#22 fix(docs): fix image path
  docs/docs/generate-data.md
  docs/docs/research.md
  docs/docs/search-results.md
  docs/docs/search.md
Labels: bug

#26 fix(users): Update list of users in cache
  src/app/user/user-form/user-form.component.ts
Labels: enhancement

#27 Update to Knora v8.0.0 and Knora-ui v8.0.0
  package.json
  yalc.lock
  yarn.lock
Labels: enhancement

#12 feat: Get app version and display in header
  package.json
  src/app/app-global.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/main/declarations/menu-item.ts
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
  src/app/main/header/header.component.spec.ts
  src/app/main/header/header.component.ts
  src/app/main/info-menu/info-menu.component.html
  src/app/main/info-menu/info-menu.component.scss
  src/app/main/info-menu/info-menu.component.spec.ts
  src/app/main/info-menu/info-menu.component.ts
  src/app/main/login/login.component.scss
  src/app/main/main.component.ts
  src/app/user/collection-list/collection-list.component.spec.ts
  src/app/user/create-menu/create-menu.component.html
  src/app/user/create-menu/create-menu.component.scss
  src/app/user/create-menu/create-menu.component.spec.ts
  src/app/user/create-menu/create-menu.component.ts
  src/app/user/profile/profile.component.html
  src/app/user/profile/profile.component.spec.ts
  src/app/user/profile/profile.component.ts
  src/app/user/user-menu/user-menu.component.html
  src/app/user/user-menu/user-menu.component.scss
  src/app/workspace/search/advanced-search/advanced-search.component.spec.ts
  src/app/workspace/search/expert-search/expert-search.component.spec.ts
  src/app/workspace/search/search.component.html
  src/app/workspace/search/search.component.scss
  src/app/workspace/search/search.component.spec.ts
  src/app/workspace/search/search.component.ts
  src/assets/images/akka-icon.svg
  src/assets/images/knora-icon.svg
  src/assets/style/_elements.scss
  src/config/config.dev.json
  src/tsconfig.app.json
Labels: enhancement

#29 Refactor: Clean up code and bug fixes
  .grenrc.js
  src/app/app-global.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
  src/app/main/info-menu/info-menu.component.html
  src/app/main/info-menu/info-menu.component.spec.ts
  src/app/main/info-menu/info-menu.component.ts
  src/app/project/collaboration/collaboration.component.ts
  src/app/project/collaboration/select-group/select-group.component.html
  src/app/project/permission/add-group/add-group.component.html
  src/app/project/permission/add-group/add-group.component.scss
  src/app/project/permission/add-group/add-group.component.spec.ts
  src/app/project/permission/add-group/add-group.component.ts
  src/app/project/permission/permission.component.html
  src/app/project/permission/permission.component.scss
  src/app/project/permission/permission.component.spec.ts
  src/app/project/permission/permission.component.ts
  src/app/system/groups/groups-list/groups-list.component.html
  src/app/system/groups/groups-list/groups-list.component.scss
  src/app/system/groups/groups-list/groups-list.component.spec.ts
  src/app/system/groups/groups-list/groups-list.component.ts
  src/app/system/groups/groups.component.html
  src/app/system/groups/groups.component.scss
  src/app/system/groups/groups.component.spec.ts
  src/app/system/groups/groups.component.ts
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/users/users-list/users-list.component.html
  src/app/system/users/users-list/users-list.component.ts
  src/app/user/dashboard/dashboard.component.html
  src/app/user/dashboard/dashboard.component.scss
  src/app/user/user-menu/user-menu.component.html
  src/app/user/user-menu/user-menu.component.scss
  src/assets/style/_elements.scss
  src/config/config.dev.json
  src/config/config.prod.json
Labels: enhancement, refactor

#28 chore: Remove Google APIs and replaced by self-hosting fonts and icons
  README.md
  package.json
  src/app/app-global.ts
  src/app/main/main.component.html
  src/app/system/projects/projects-list/projects-list.component.html
  src/app/system/status/status.component.html
  src/app/user/user-menu/user-menu.component.html
  src/app/user/user-menu/user-menu.component.ts
  src/app/user/user.component.html
  src/assets/fonts/roboto-v19-latin-300.eot
  src/assets/fonts/roboto-v19-latin-300.svg
  src/assets/fonts/roboto-v19-latin-300.ttf
  src/assets/fonts/roboto-v19-latin-300.woff
  src/assets/fonts/roboto-v19-latin-300.woff2
  src/assets/fonts/roboto-v19-latin-500.eot
  src/assets/fonts/roboto-v19-latin-500.svg
  src/assets/fonts/roboto-v19-latin-500.ttf
  src/assets/fonts/roboto-v19-latin-500.woff
  src/assets/fonts/roboto-v19-latin-500.woff2
  src/assets/fonts/roboto-v19-latin-700.eot
  src/assets/fonts/roboto-v19-latin-700.svg
  src/assets/fonts/roboto-v19-latin-700.ttf
  src/assets/fonts/roboto-v19-latin-700.woff
  src/assets/fonts/roboto-v19-latin-700.woff2
  src/assets/fonts/roboto-v19-latin-italic.eot
  src/assets/fonts/roboto-v19-latin-italic.svg
  src/assets/fonts/roboto-v19-latin-italic.ttf
  src/assets/fonts/roboto-v19-latin-italic.woff
  src/assets/fonts/roboto-v19-latin-italic.woff2
  src/assets/fonts/roboto-v19-latin-regular.eot
  src/assets/fonts/roboto-v19-latin-regular.svg
  src/assets/fonts/roboto-v19-latin-regular.ttf
  src/assets/fonts/roboto-v19-latin-regular.woff
  src/assets/fonts/roboto-v19-latin-regular.woff2
  src/assets/style/_elements.scss
  src/assets/style/_font.scss
  src/assets/style/_theme.scss
  src/assets/style/main.scss
  src/index.html
  src/styles.scss
  yarn.lock
Labels: enhancement

#30 refactor(expert-search): Add expert-search from knora-ui search module
  src/app/workspace/search/expert-search/expert-search.component.html
  src/app/workspace/search/expert-search/expert-search.component.scss
  src/app/workspace/search/expert-search/expert-search.component.ts
Labels: refactor

#33 fix(workspace): Reload search results
  src/app/app-routing.module.ts
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.ts
  src/app/workspace/search/advanced-search/advanced-search.component.html
  src/app/workspace/search/advanced-search/advanced-search.component.ts
  src/app/workspace/search/expert-search/expert-search.component.ts
Labels: bug

#32 Refactor: Clean up code, bug fixes, style optimization
  package.json
  src/app/main/info-menu/info-menu.component.ts
  src/app/main/main.component.html
  src/app/main/main.component.scss
  src/app/main/main.component.ts
  src/app/system/projects/projects-list/projects-list.component.html
  src/app/system/projects/projects-list/projects-list.component.ts
  yarn.lock
Labels: bug, enhancement, refactor
