Repository dasch-swiss/dsp-das, pull requests merged in 2019-08, with the labels that each got.

#38 style: Redesign layout to make it phone responsive
  src/app/app-global.ts
  src/app/main/declarations/menu-item.ts
  src/app/main/error/error.component.scss
  src/app/main/grid/grid.component.scss
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
  src/app/main/header/header.component.ts
  src/app/main/main.component.html
  src/app/main/main.component.scss
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/collaboration/add-user/add-user.component.html
  src/app/project/collaboration/add-user/add-user.component.scss
  src/app/project/project.component.scss
  src/app/system/projects/projects-list/projects-list.component.html
  src/app/system/projects/projects-list/projects-list.component.scss
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/projects/projects.component.html
  src/app/system/system.component.html
  src/app/system/system.component.scss
  src/app/system/users/users-list/users-list.component.html
  src/app/system/users/users-list/users-list.component.scss
  src/app/user/account/account.component.scss
  src/app/user/dashboard/dashboard.component.html
  src/app/user/dashboard/dashboard.component.scss
  src/app/user/profile/profile.component.html
  src/app/user/profile/profile.component.scss
  src/app/user/user-menu/user-menu.component.scss
  src/app/user/user.component.html
  src/app/user/user.component.scss
  src/assets/style/_responsive.scss
Labels: enhancement

#51 feat(users list): Disable "remove as sys admin" on own profile
  src/app/system/users/users-list/users-list.component.html
Labels: enhancement

#52 feat(main): Improve landing page
  src/app/main/main.component.html
  src/app/main/main.component.ts
Labels: complexity/low, enhancement

#54 style: Fix position of mat-menu and box-shadow
  src/assets/style/_elements.scss
Labels: bug, stage/code-review, style

#46 feat: Better password form handling
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.spec.ts
  src/app/system/users/users-list/users-list.component.html
  src/app/system/users/users-list/users-list.component.ts
  src/app/user/account/account.component.html
  src/app/user/account/account.component.spec.ts
  src/app/user/user-form/password-form/password-form.component.html
  src/app/user/user-form/password-form/password-form.component.scss
  src/app/user/user-form/password-form/password-form.component.spec.ts
  src/app/user/user-form/password-form/password-form.component.ts
  src/app/user/user-form/user-form.component.html
  src/app/user/user-form/user-form.component.scss
  src/app/user/user-form/user-form.component.spec.ts
  src/app/user/user-form/user-form.component.ts
  src/app/user/user-form/user-password/user-password.component.html
  src/app/user/user-form/user-password/user-password.component.scss
  src/app/user/user-form/user-password/user-password.component.ts
  src/app/user/user.component.spec.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/style/_elements.scss
Labels: enhancement, stage/code-review

#56 feat: system view > manage user's project membership
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.spec.ts
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/users/users-list/users-list.component.html
  src/app/system/users/users-list/users-list.component.ts
  src/app/user/membership/membership.component.html
  src/app/user/membership/membership.component.scss
  src/app/user/membership/membership.component.spec.ts
  src/app/user/membership/membership.component.ts
  src/app/user/user-form/user-form.component.html
Labels: enhancement, stage/code-review

#57 Pre-release v1.4.0
  package.json
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/user/dashboard/dashboard.component.html
  src/assets/style/_layout.scss
  yarn.lock
Labels: enhancement

#35 chore: Upgrade to Angular version 8
  browserslist
  package.json
  src/app/app.component.spec.ts
  src/app/main/cookie-policy/cookie-policy.component.spec.ts
  src/app/main/dialog/dialog-header/dialog-header.component.spec.ts
  src/app/main/dialog/dialog.component.spec.ts
  src/app/main/dialog/dialog.component.ts
  src/app/main/grid/grid.component.spec.ts
  src/app/main/header/header.component.spec.ts
  src/app/main/info-menu/info-menu.component.spec.ts
  src/app/main/info-menu/info-menu.component.ts
  src/app/main/main.component.spec.ts
  src/app/main/select-language/select-language.component.spec.ts
  src/app/material-module.ts
  src/app/project/board/board.component.spec.ts
  src/app/project/board/board.component.ts
  src/app/project/collaboration/add-user/add-user.component.spec.ts
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/project/collaboration/collaboration.component.spec.ts
  src/app/project/collaboration/collaboration.component.ts
  src/app/project/collaboration/select-group/select-group.component.spec.ts
  src/app/project/ontology/ontology.component.spec.ts
  src/app/project/ontology/ontology.component.ts
  src/app/project/permission/permission.component.ts
  src/app/project/project-form/project-form.component.spec.ts
  src/app/project/project-form/project-form.component.ts
  src/app/project/project.component.spec.ts
  src/app/system/projects/projects-list/projects-list.component.spec.ts
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/projects/projects.component.spec.ts
  src/app/system/projects/projects.component.ts
  src/app/system/system.component.spec.ts
  src/app/system/users/users-list/users-list.component.spec.ts
  src/app/system/users/users-list/users-list.component.ts
  src/app/system/users/users.component.spec.ts
  src/app/user/account/account.component.spec.ts
  src/app/user/account/account.component.ts
  src/app/user/dashboard/dashboard.component.spec.ts
  src/app/user/profile/profile.component.spec.ts
  src/app/user/profile/profile.component.ts
  src/app/user/user-form/password-form/password-form.component.spec.ts
  src/app/user/user-form/user-form.component.spec.ts
  src/app/user/user-menu/user-menu.component.spec.ts
  src/app/user/user.component.spec.ts
  src/app/user/user.component.ts
  src/app/workspace/resource/resource.component.spec.ts
  src/app/workspace/search/advanced-search/advanced-search.component.spec.ts
  src/app/workspace/search/expert-search/expert-search.component.spec.ts
  src/assets/style/_responsive.scss
  tsconfig.json
  tslint.json
  yarn.lock
Labels: enhancement, stage/waiting

#68 chore: Update to Knora-UI v9.0.0
  package.json
  yarn.lock
Labels: enhancement
