Repository dasch-swiss/dsp-das, pull requests merged in 2019-09, with the labels that each got.

#73 chore: Update gren info
  .grenrc.js
Labels: chore

#74 refactor(resource): Rename button Back
  src/app/workspace/resource/resource.component.html
Labels: refactor

#75 Edit list nodes
  angular.json
  package.json
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/project/list/list-info-form/list-info-form.component.scss
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.ts
  src/app/project/list/list-item-form/list-item-form.component.html
  src/app/project/list/list-item-form/list-item-form.component.scss
  src/app/project/list/list-item-form/list-item-form.component.spec.ts
  src/app/project/list/list-item-form/list-item-form.component.ts
  src/app/project/list/list-item/list-item.component.html
  src/app/project/list/list-item/list-item.component.scss
  src/app/project/list/list-item/list-item.component.spec.ts
  src/app/project/list/list-item/list-item.component.ts
  src/app/project/list/list-items-form/list-items-form.component.html
  src/app/project/list/list-items-form/list-items-form.component.scss
  src/app/project/list/list-items-form/list-items-form.component.spec.ts
  src/app/project/list/list-items-form/list-items-form.component.ts
  src/app/project/list/list-items/list-items.component.html
  src/app/project/list/list-items/list-items.component.scss
  src/app/project/list/list-items/list-items.component.spec.ts
  src/app/project/list/list-items/list-items.component.ts
  src/app/project/list/list.component.html
  src/app/project/list/list.component.scss
  src/app/project/list/list.component.spec.ts
  src/app/project/list/list.component.ts
  src/app/project/list/lists-list/lists-list.component.html
  src/app/project/list/lists-list/lists-list.component.scss
  src/app/project/list/lists-list/lists-list.component.spec.ts
  src/app/project/list/lists-list/lists-list.component.ts
  yarn.lock
Labels: enhancement, stage/code-review

#83 Implementation of new Knora-ui authentication
  package.json
  src/app/main/header/header.component.ts
  src/app/main/login/login.component.html
  src/app/main/login/login.component.ts
  src/app/user/user-menu/user-menu.component.ts
  yarn.lock
Labels: bug, stage/waiting

#86 Update angular
  package.json
  yarn.lock
Labels: warning

#87 Implement latest version of search panel
  angular.json
  package.json
  yarn.lock
Labels: enhancement, stage/waiting

#92 Fix style issue in lists
  src/app/project/list/list-item-form/list-item-form.component.html
  src/app/project/list/list-item-form/list-item-form.component.scss
  src/app/project/list/list-item/list-item.component.html
  src/app/project/list/list-item/list-item.component.scss
Labels: bug, styling
