Repository dasch-swiss/dsp-das, pull requests merged in 2020-12, with the labels that each got.

#331 DSP-1061 Form select box functionality polish
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.html
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.scss
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.html
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.scss
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.scss
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
Labels: enhancement

#337 DSP-1127 Rename header titles and resource placeholders
  src/app/main/header/header.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html
Labels: refactor

#334 DSP-943 - Resource Form Add Additional Value
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts
Labels: enhancement

#338 DSP-1136 - Select-Properties Component CSS Quick Fix
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
Labels: bug

#339 DSP-694 Bug fix in project view when not logged-in
  src/app/project/board/board.component.ts
Labels: bug

#324 DSP-861 Create resource property
  package-lock.json
  package.json
  src/app/project/list/list.component.html
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.scss
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.scss
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
  src/assets/style/_elements.scss
Labels: enhancement

#340 DSP-1146 Use new methods for ontology info processing
  package-lock.json
  package.json
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.spec.ts
Labels: refactor

#344 DSP-1161 Add error handling in the new resource form
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.html
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.html
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html
Labels: enhancement

#346 Wip/dsp 1168 Release please action instead release drafter
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
  package-lock.json
  package.json
  vars.mk
Labels: chore

#345 DSP-1128 Trim whitespace from resource label
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
Labels: enhancement

#349 Update DSP-UI and DSP-JS
  .github/workflows/main.yml
  package-lock.json
  package.json
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/default-data/default-resource-classes.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
Labels: dependencies

#352 Update package-name in gh actions workflow
  .github/workflows/main.yml
Labels: chore
