Repository dasch-swiss/dsp-das, pull requests merged in 2020-09, with the labels that each got.

#285 Integrate OntoVis
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.html
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.ts
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.html
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.scss
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.spec.ts
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.ts
  src/app/project/ontology/ontology.component.spec.ts
Labels: enhancement, ontology

#286 Get dsp-api version from the api server info
  package.json
  src/app/main/help/help.component.ts
Labels: enhancement

#287 Replace the term source by resource
  README.md
  package-lock.json
  src/app/main/dialog/dialog.component.html
  src/app/main/help/help.component.ts
  src/app/main/main.component.html
  src/app/main/main.component.ts
Labels: refactor

#288 DSP-420 update release process
  .github/workflows/main.yml
  .grenrc
  CHANGELOG.md
  Makefile
  README.md
Labels: build, chore

#290 DSP-617 Use release-drafter instead gren
  .github/release-drafter.yml
  .github/workflows/main.yml
Labels: chore

#291 DSP-617 Update release process
  .github/release-drafter.yml
  .github/workflows/main.yml
  .grenrc
  CHANGELOG.md
  Makefile
  README.md
  package-lock.json
  package.json
Labels: chore

#292 docs: Update README
  README.md
Labels: documentation

#293 Update js- and ui-lib version
  package-lock.json
  package.json
Labels: dependencies

#294 Fix: Update docker environment
  CHANGELOG.md
  Dockerfile
  Makefile
  package-lock.json
  package.json
Labels: bug, release

#296 Update README.md
  README.md
Labels: documentation

#295 Login Success Message
  .gitignore
  package.json
  src/app/app.component.html
  src/app/main/header/header.component.html
  src/app/main/header/header.component.spec.ts
  src/app/main/header/header.component.ts
  src/app/main/login/login.component.ts
  src/app/services/component-communication-event.service.spec.ts
  src/app/services/component-communication-event.service.ts
Labels: enhancement

#297 DSP-295 Open external link in new tab
  src/app/main/footer/footer.component.html
  src/app/main/main.component.html
Labels: chore

#299 Fix tiny issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/testing-bug.md
  README.md
  package-lock.json
  src/config/config.prod.json
  vars.mk
Labels: chore

#298 DSP-298 Add app name to header
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
  src/app/main/header/header.component.ts
  src/assets/images/dasch-icon-black.svg
  src/assets/images/dasch-icon-purple.svg
  src/assets/images/dasch-icon-white.svg
Labels: styling

#300 DSP-673 Update dependency
  CHANGELOG.md
  angular.json
  package-lock.json
  package.json
  vars.mk
Labels: dependencies

#302 DSP-371 - Improve the visibility of expert and advanced search links
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
Labels: styling

#304 DSP-666 Fix issue with version number
  src/app/main/help/help.component.ts
Labels: bug

#305 DSP-669 Add template for PRs
  .github/pull_request_template.md
Labels: chore

#306 DSP-700 Fix broken link to project
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
Labels: bug

#307 DSP-368 - Redundancy with Cancel button and close button in dialog boxes
  src/app/main/dialog/dialog-header/dialog-header.component.html
  src/app/main/dialog/dialog.component.html
  src/app/user/user-form/password-form/password-form.component.html
Labels: refactor

#309 DSP-689 Resource viewer fix style in properties toolbar
  src/assets/style/_responsive.scss
Labels: styling

#310 DSP-339 - Add a link to the membership management page from the system project page
  src/app/system/projects/projects-list/projects-list.component.html
  src/app/system/projects/projects-list/projects-list.component.ts
Labels: enhancement

#308 DSP-284 Display app version in header
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
  src/app/main/header/header.component.ts
  src/assets/style/_config.scss
  src/assets/style/_elements.scss
Labels: enhancement
