Repository dasch-swiss/dsp-das, pull requests merged in 2020-11, with the labels that each got.

#326 Update dsp dependencies
  .editorconfig
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
  src/app/main/header/header.component.spec.ts
  src/app/main/header/header.component.ts
  src/app/main/help/help.component.spec.ts
  src/app/main/help/help.component.ts
  src/app/main/main.component.ts
  src/app/material-module.ts
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.spec.ts
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.spec.ts
  src/app/workspace/results/results.component.ts
  src/app/workspace/search/advanced-search/advanced-search.component.html
  src/app/workspace/search/advanced-search/advanced-search.component.scss
  src/app/workspace/search/advanced-search/advanced-search.component.spec.ts
  src/app/workspace/search/advanced-search/advanced-search.component.ts
  src/app/workspace/search/expert-search/expert-search.component.html
  src/app/workspace/search/expert-search/expert-search.component.scss
  src/app/workspace/search/expert-search/expert-search.component.spec.ts
  src/app/workspace/search/expert-search/expert-search.component.ts
  src/assets/style/_elements.scss
  src/assets/style/_responsive.scss
  src/index.html
Labels: dependencies, enhancement, styling

#327 Update dependencies
  .github/workflows/main.yml
  .gitignore
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
Labels: dependencies

#321 DSP-851 New resource form
  src/app/app.module.ts
  src/app/base-value.component.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/header/header.component.html
  src/app/main/header/header.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.html
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.scss
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.html
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.scss
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.scss
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.scss
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
Labels: enhancement

#328 DSP-1069 - Create Resource Form V1 Polish
  src/app/main/header/header.component.ts
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
Labels: enhancement

#329 DSP-1062 - Form "back" button functionality polish
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-ontology/select-ontology.component.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
Labels: enhancement

#332 DSP-1085 Hide link to the resource form in the header when logged out
  src/app/main/header/header.component.html
Labels: enhancement

#333 DSP-1098 - Bump JS-Lib Version and Fix Breaking Changes
  package-lock.json
  package.json
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
Labels: chore

#330 Dsp 945 resource viewer
  package.json
  src/app/app.module.ts
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.scss
  src/app/workspace/results/results.component.ts
Labels: enhancement

#335 Update DSP-JS-Lib and DSP-UI-Lib to latest version
  package-lock.json
  package.json
  src/app/main/help/help.component.ts
  src/app/project/ontology/ontology.component.html
Labels: dependencies

#336 DSP-1110 Improve resource viewer
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.scss
  src/app/workspace/results/results.component.ts
Labels: enhancement, refactor, styling
