Repository dasch-swiss/dsp-das, pull requests merged in 2020-10, with the labels that each got.

#312 DSP-766 Remove 'de' from list of available languages
  src/app/main/select-language/select-language.component.ts
Labels: chore

#313 DSP-674 Replace search-panel with fulltext-search
  src/app/main/header/header.component.html
  src/app/main/header/header.component.spec.ts
Labels: bug

#314 DSP-297 - Make the external links easy to spot
  src/app/app.module.ts
  src/app/main/directive/external-links.directive.spec.ts
  src/app/main/directive/external-links.directive.ts
  src/assets/style/_elements.scss
Labels: enhancement

#315 Move services folder to main folder
  src/app/main/header/header.component.spec.ts
  src/app/main/header/header.component.ts
  src/app/main/login/login.component.ts
  src/app/main/services/component-communication-event.service.spec.ts
  src/app/main/services/component-communication-event.service.ts
Labels: chore

#316 DSP-293 Update contact information on the landing page
  src/app/main/footer/footer.component.html
  src/app/main/main.component.html
Labels: refactor

#317 Update js-lib and ui-lib
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
Labels: dependencies

#303 DSP-329 Fix sort button
  src/app/system/projects/projects-list/projects-list.component.html
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/users/users-list/users-list.component.html
  src/app/system/users/users-list/users-list.component.ts
Labels: bug, enhancement

#318 Update dependencies
  package-lock.json
  package.json
Labels: dependencies

#320 DSP-850 Navigation and dialog box to create a new resource
  src/app/main/dialog/dialog.component.html
  src/app/main/header/header.component.html
  src/app/main/header/header.component.ts
  src/assets/i18n/en.json
  src/assets/style/_elements.scss
Labels: enhancement

#322 DSP-860: Ontology editor: Create resource class
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.scss
  src/app/main/dialog/dialog.component.ts
  src/app/project/ontology/default-data/default-resource-classes.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
Labels: enhancement

#323 DSP-908 - Project List Sorting Fix
  src/app/system/projects/projects-list/projects-list.component.ts
Labels: bug

#325 DSP-920 Renaming default github branch to "main"
  .github/pull_request_template.md
  .github/workflows/main.yml
Labels: chore
