Repository dasch-swiss/dsp-das, pull requests merged in 2020-01, with the labels that each got.

#221 Fix issues on cache service
  src/app/main/cache/cache.service.ts
  src/app/main/header/header.component.ts
  src/app/project/board/board.component.ts
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/project/collaboration/collaboration.component.ts
  src/app/project/list/list.component.ts
  src/app/project/permission/permission.component.html
  src/app/project/permission/permission.component.ts
  src/app/project/project-form/project-form.component.ts
  src/app/project/project.component.html
  src/app/project/project.component.ts
  src/app/system/users/users-list/users-list.component.ts
  src/app/user/user.component.ts
Labels: bug

#236 Split knora version number without extra suffix
  src/app/main/help/help.component.ts
Labels: bug

#232 Add some unit tests and e2e tests
  .circleci/config.yml
  .travis.yml
  e2e/protractor-ci.conf.js
  e2e/protractor.conf.js
  e2e/src/app.e2e-spec.ts
  e2e/src/app.po.ts
  e2e/src/help.e2e-spec.ts
  e2e/src/login.e2e-spec.ts
  e2e/src/page-objects/app.po.ts
  e2e/src/page-objects/help.po.ts
  e2e/src/page-objects/login.po.ts
  package.json
  src/app/main/help/help.component.ts
  src/app/main/main.component.html
  src/app/main/main.component.spec.ts
Labels: testing

#246 Fix broken link to Knora release notes page
  src/app/main/help/help.component.ts
Labels: bug

#247 Resolve security alert about serialize-javascript
  yarn.lock
Labels: warning

#249 Upgrade knora-api-js-lib to v0.2.0
  package.json
  yarn.lock
Labels: chore

#250 Pre release v2.0.1
  README.md
  package.json
  src/app/main/cache/cache.service.ts
  yarn.lock
Labels: chore, documentation, enhancement
