Repository dasch-swiss/dsp-das, pull requests merged in 2021-04, with the labels that each got.

#412 chore(migrate to angular10): changes (DSP-1415)
  .browserslistrc
  angular.json
  package-lock.json
  package.json
  src/assets/style/_font.scss
  tsconfig.json
Labels: chore

#417 fix(ontology): Bug fix in ontology form (DSP-1526)
  src/app/main/dialog/dialog.component.html
Labels: bug

#419 fix(users): update session the correct way (DSP-690)
  src/app/system/users/users-list/users-list.component.ts
Labels: bug

#421 feat(project): better error handler in case a project does not exist (DSP-1401)
  src/app/project/board/board.component.ts
  src/app/project/collaboration/collaboration.component.ts
  src/app/project/list/list.component.spec.ts
  src/app/project/list/list.component.ts
  src/app/project/ontology/ontology.component.ts
  src/app/project/permission/permission.component.ts
  src/app/project/project.component.html
  src/app/project/project.component.ts
  src/app/system/users/users-list/users-list.component.ts
Labels: bug, enhancement

#423 fix(ontology): bug fix in create ontology process (DSP-1558)
  src/app/project/ontology/ontology-form/ontology-form.component.ts
Labels: bug

#425 fix(project): bug fix in project member management (DSP-1563)
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/project/project-form/project-form.component.ts
  src/app/user/user-form/user-form.component.ts
Labels: bug

#426 refactor(ontology): rename boolean prop type (DSP-1561)
  src/app/project/ontology/default-data/default-properties.ts
Labels: refactor

#427 refactor(ontology): disable ontology graph view (DSP-1560)
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.html
  src/app/project/ontology/ontology.component.html
Labels: refactor

#429 fix(list): list deletion
  src/app/project/list/list.component.spec.ts
  src/app/project/list/list.component.ts
Labels: bug

#430 refactor(ontology): disable rti image class (DSP-1559)
  src/app/project/ontology/default-data/default-resource-classes.ts
Labels: refactor

#431 feat(DMP): bring back the workspace
  package-lock.json
  src/app/app-routing.module.ts
  src/app/main/header/header.component.html
Labels: enhancement
