Repository dasch-swiss/dsp-das, pull requests merged in 2021-08, with the labels that each got.

#492 feat(resource): update resource's label (DSP-1801)
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.scss
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.ts
Labels: enhancement

#493 Improve error handler and fix search results issue (DSP-1826 / DSP-1831)
  package-lock.json
  package.json
  src/app/main/cache/cache.service.spec.ts
  src/app/main/error/error-handler.service.spec.ts
  src/app/main/error/error-handler.service.ts
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/board/board.component.ts
  src/app/workspace/resource/properties/properties.component.spec.ts
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.ts
Labels: enhancement, refactor

#495 chore(deps): bump dsp-ui to latest version (DSP-1838)
  package-lock.json
  package.json
Labels: dependencies

#494 feat(workspace): add intermediate view (DSP-1834)
  src/app/app.module.ts
  src/app/workspace/intermediate/intermediate.component.html
  src/app/workspace/intermediate/intermediate.component.scss
  src/app/workspace/intermediate/intermediate.component.spec.ts
  src/app/workspace/intermediate/intermediate.component.ts
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.ts
Labels: enhancement

#500 chore(ontology): update create ontology tooltip for unique name (DSP-1139)
  src/app/project/ontology/ontology-form/ontology-form.component.ts
Labels: chore

#501 feat(resource): create link / collection resource (DSP-1835)
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.ts
  src/app/workspace/intermediate/intermediate.component.html
  src/app/workspace/intermediate/intermediate.component.spec.ts
  src/app/workspace/intermediate/intermediate.component.ts
  src/app/workspace/resource/project.service.spec.ts
  src/app/workspace/resource/project.service.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.html
  src/app/workspace/resource/resource-link-form/resource-link-form.component.scss
  src/app/workspace/resource/resource-link-form/resource-link-form.component.spec.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.ts
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.ts
Labels: enhancement

#502 chore(deps): bump dsp-ui to latest
  package-lock.json
  package.json
  src/assets/style/_elements.scss
Labels: dependencies

#507 feat(resource): display incoming links (DSP-1846)
  src/app/workspace/resource/incoming.service.ts
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.scss
  src/app/workspace/resource/properties/properties.component.spec.ts
  src/app/workspace/resource/properties/properties.component.ts
Labels: enhancement

#505 refactor(core): migrate core module from UI-lib (DSP-1853)
  src/app/main/declarations/dsp-api-tokens.ts
  src/app/main/services/app-init.service.spec.ts
  src/app/main/services/app-init.service.ts
  src/app/main/services/session.service.spec.ts
  src/app/main/services/session.service.ts
Labels: refactor

#509 refactor(action): migrate action module (DSP-1852)
  package-lock.json
  src/app/app.module.ts
  src/app/main/action/confirmation-dialog/confirmation-dialog.component.html
  src/app/main/action/confirmation-dialog/confirmation-dialog.component.scss
  src/app/main/action/confirmation-dialog/confirmation-dialog.component.spec.ts
  src/app/main/action/confirmation-dialog/confirmation-dialog.component.ts
  src/app/main/action/confirmation-dialog/confirmation-message/confirmation-message.component.html
  src/app/main/action/confirmation-dialog/confirmation-message/confirmation-message.component.scss
  src/app/main/action/confirmation-dialog/confirmation-message/confirmation-message.component.spec.ts
  src/app/main/action/confirmation-dialog/confirmation-message/confirmation-message.component.ts
  src/app/main/action/login-form/login-form.component.html
  src/app/main/action/login-form/login-form.component.scss
  src/app/main/action/login-form/login-form.component.spec.ts
  src/app/main/action/login-form/login-form.component.ts
  src/app/main/action/message/message.component.html
  src/app/main/action/message/message.component.scss
  src/app/main/action/message/message.component.spec.ts
  src/app/main/action/message/message.component.ts
  src/app/main/action/progress-indicator/progress-indicator.component.html
  src/app/main/action/progress-indicator/progress-indicator.component.scss
  src/app/main/action/progress-indicator/progress-indicator.component.spec.ts
  src/app/main/action/progress-indicator/progress-indicator.component.ts
  src/app/main/action/selected-resources/selected-resources.component.html
  src/app/main/action/selected-resources/selected-resources.component.scss
  src/app/main/action/selected-resources/selected-resources.component.spec.ts
  src/app/main/action/selected-resources/selected-resources.component.ts
  src/app/main/action/sort-button/sort-button.component.html
  src/app/main/action/sort-button/sort-button.component.scss
  src/app/main/action/sort-button/sort-button.component.spec.ts
  src/app/main/action/sort-button/sort-button.component.ts
  src/app/main/action/string-literal-input/string-literal-input.component.html
  src/app/main/action/string-literal-input/string-literal-input.component.scss
  src/app/main/action/string-literal-input/string-literal-input.component.spec.ts
  src/app/main/action/string-literal-input/string-literal-input.component.ts
  src/app/main/directive/admin-image/admin-image.config.ts
  src/app/main/directive/admin-image/admin-image.directive.spec.ts
  src/app/main/directive/admin-image/admin-image.directive.ts
  src/app/main/directive/existing-name/existing-name.directive.spec.ts
  src/app/main/directive/existing-name/existing-name.directive.ts
  src/app/main/directive/gnd/gnd.directive.spec.ts
  src/app/main/directive/gnd/gnd.directive.ts
  src/app/main/pipes/formatting/formatted-boolean.pipe.spec.ts
  src/app/main/pipes/formatting/formatted-boolean.pipe.ts
  src/app/main/pipes/formatting/knoradate.pipe.spec.ts
  src/app/main/pipes/formatting/knoradate.pipe.ts
  src/app/main/pipes/string-transformation/linkify.pipe.spec.ts
  src/app/main/pipes/string-transformation/linkify.pipe.ts
  src/app/main/pipes/string-transformation/stringify-string-literal.pipe.spec.ts
  src/app/main/pipes/string-transformation/stringify-string-literal.pipe.ts
  src/app/main/pipes/string-transformation/truncate.pipe.spec.ts
  src/app/main/pipes/string-transformation/truncate.pipe.ts
  src/app/main/services/notification.service.spec.ts
  src/app/main/services/notification.service.ts
  src/app/main/services/sorting.service.spec.ts
  src/app/main/services/sorting.service.ts
  src/assets/http/statusMsg.ts
  src/assets/style/_viewer.scss
Labels: refactor

#503 chore(project): handle mandatory keyword field (DSP-1829)
  src/app/project/project-form/project-form.component.html
  src/app/project/project-form/project-form.component.ts
Labels: enhancement, chore
