Repository dasch-swiss/dsp-das, pull requests merged in 2021-12, with the labels that each got.

#599 chore(lists): fix lists functionality that broke due to js-lib changes (DEV-273)
  package-lock.json
  package.json
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts
  src/app/project/list/list-item-form/list-item-form.component.ts
Labels: chore

#600 feat(representation): add support for uploading and viewing archive files (DEV-18)
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/project/ontology/default-data/default-resource-classes.ts
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/representation/archive/archive.component.html
  src/app/workspace/resource/representation/archive/archive.component.scss
  src/app/workspace/resource/representation/archive/archive.component.spec.ts
  src/app/workspace/resource/representation/archive/archive.component.ts
  src/app/workspace/resource/representation/file-representation.ts
  src/app/workspace/resource/representation/upload/upload.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-resource-class/search-select-resource-class.component.spec.ts
  src/assets/style/_elements.scss
Labels: enhancement

#602 fix(value): fix linkify pipe (DEV-270)
  src/app/main/pipes/string-transformation/linkify.pipe.spec.ts
  src/app/main/pipes/string-transformation/linkify.pipe.ts
Labels: bug

#603 fix(ontology): bug fix in ontology form (DEV-280)
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.ts
Labels: bug

#604 chore(deps): update outdated angular packages
  package-lock.json
  package.json
Labels: dependencies

#605 fix(resource): create resource iri from route only in certain cases (DEV-306)
  src/app/workspace/resource/resource.component.ts
Labels: bug

#606 fix(angular): fix budget in prod mode
  angular.json
Labels: chore

#609 chore: release 8.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#612 chore: release 8.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#616 fix(resource): update lastModificationDate after editing label (DEV-315)
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.scss
  src/app/workspace/resource/properties/properties.component.ts
Labels: bug

#620 refactor(google fonts): switch to using fonts hosted by google (DEV-321)
  src/assets/style/_font.scss
  src/assets/style/main.scss
  src/index.html
Labels: refactor

#619 fix(upload): fix thumbnail preview (DEV-268)
  src/app/workspace/resource/representation/upload/upload.component.html
  src/app/workspace/resource/representation/upload/upload.component.ts
Labels: bug

#623 refactor(fonts): delete fonts and icons (DEV-327)
  src/assets/fonts/material-icons/MaterialIcons-Regular.eot
  src/assets/fonts/material-icons/MaterialIcons-Regular.svg
  src/assets/fonts/material-icons/MaterialIcons-Regular.ttf
  src/assets/fonts/material-icons/MaterialIcons-Regular.woff
  src/assets/fonts/material-icons/MaterialIcons-Regular.woff2
  src/assets/fonts/roboto/roboto-v19-latin-300.eot
  src/assets/fonts/roboto/roboto-v19-latin-300.svg
  src/assets/fonts/roboto/roboto-v19-latin-300.ttf
  src/assets/fonts/roboto/roboto-v19-latin-300.woff
  src/assets/fonts/roboto/roboto-v19-latin-300.woff2
  src/assets/fonts/roboto/roboto-v19-latin-500.eot
  src/assets/fonts/roboto/roboto-v19-latin-500.svg
  src/assets/fonts/roboto/roboto-v19-latin-500.ttf
  src/assets/fonts/roboto/roboto-v19-latin-500.woff
  src/assets/fonts/roboto/roboto-v19-latin-500.woff2
  src/assets/fonts/roboto/roboto-v19-latin-700.eot
  src/assets/fonts/roboto/roboto-v19-latin-700.svg
  src/assets/fonts/roboto/roboto-v19-latin-700.ttf
  src/assets/fonts/roboto/roboto-v19-latin-700.woff
  src/assets/fonts/roboto/roboto-v19-latin-700.woff2
  src/assets/fonts/roboto/roboto-v19-latin-italic.eot
  src/assets/fonts/roboto/roboto-v19-latin-italic.svg
  src/assets/fonts/roboto/roboto-v19-latin-italic.ttf
  src/assets/fonts/roboto/roboto-v19-latin-italic.woff
  src/assets/fonts/roboto/roboto-v19-latin-italic.woff2
  src/assets/fonts/roboto/roboto-v19-latin-regular.eot
  src/assets/fonts/roboto/roboto-v19-latin-regular.svg
  src/assets/fonts/roboto/roboto-v19-latin-regular.ttf
  src/assets/fonts/roboto/roboto-v19-latin-regular.woff
  src/assets/fonts/roboto/roboto-v19-latin-regular.woff2
Labels: refactor

#624 fix(authentication): set active datadog rum user (DEV-325)
  src/app/main/services/authentication.service.spec.ts
  src/app/main/services/datadog-rum.service.ts
Labels: bug
