Repository dasch-swiss/dsp-das, pull requests merged in 2021-01, with the labels that each got.

#353 chore: update pr template (DSP-1189)
  .github/pull_request_template.md
Labels: chore

#348 feat: display metadata on project landing page (DSP-1065)
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/project/board/address-template/address-template.component.ts
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.html
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.scss
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.spec.ts
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.ts
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/board/board.component.spec.ts
  src/app/project/board/board.component.ts
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.html
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.scss
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.spec.ts
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.ts
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.html
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.scss
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.spec.ts
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.ts
  src/app/project/board/organisation-template/organisation-template.component.ts
  src/app/project/board/person-template/person-template.component.html
  src/app/project/board/person-template/person-template.component.scss
  src/app/project/board/person-template/person-template.component.spec.ts
  src/app/project/board/person-template/person-template.component.ts
  src/app/project/board/project-tab-view/project-tab-view.component.html
  src/app/project/board/project-tab-view/project-tab-view.component.scss
  src/app/project/board/project-tab-view/project-tab-view.component.spec.ts
  src/app/project/board/project-tab-view/project-tab-view.component.ts
  src/app/project/board/terms-tab-view/terms-tab-view.component.html
  src/app/project/board/terms-tab-view/terms-tab-view.component.scss
  src/app/project/board/terms-tab-view/terms-tab-view.component.spec.ts
  src/app/project/board/terms-tab-view/terms-tab-view.component.ts
  src/assets/images/cc-license.png
  src/assets/style/_config.scss
Labels: enhancement

#357 feat (project landing page): download metadata in JSON format (DSP-1184)
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/board/board.component.ts
Labels: enhancement

#358 fix(dialog): Fixed dialog box height issue (DSP-1211)
  src/app/main/header/header.component.ts
  src/app/project/board/board.component.ts
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/project/list/list.component.ts
  src/app/project/ontology/ontology.component.ts
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/projects/projects.component.ts
  src/app/system/users/users-list/users-list.component.ts
  src/app/user/account/account.component.ts
  src/app/user/profile/profile.component.ts
Labels: bug, styling

#359 test: import missing modules
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/main/cache/cache.service.spec.ts
  src/app/main/dialog/dialog.component.spec.ts
  src/app/main/error/error.component.spec.ts
  src/app/main/help/help.component.spec.ts
  src/app/main/main.component.spec.ts
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.spec.ts
  src/app/project/board/board.component.spec.ts
  src/app/project/board/board.component.ts
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.spec.ts
  src/app/project/board/person-template/person-template.component.spec.ts
  src/app/project/board/project-tab-view/project-tab-view.component.html
  src/app/project/board/project-tab-view/project-tab-view.component.spec.ts
  src/app/project/collaboration/add-user/add-user.component.spec.ts
  src/app/project/collaboration/collaboration.component.spec.ts
  src/app/project/collaboration/select-group/select-group.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/list/list-item-form/list-item-form.component.spec.ts
  src/app/project/list/list-item/list-item.component.spec.ts
  src/app/project/list/list.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.ts
  src/app/project/ontology/ontology.component.spec.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.spec.ts
  src/app/project/permission/permission.component.spec.ts
  src/app/project/project-form/project-form.component.spec.ts
  src/app/project/project.component.spec.ts
  src/app/system/projects/projects-list/projects-list.component.spec.ts
  src/app/system/projects/projects.component.spec.ts
  src/app/system/status/status.component.html
  src/app/system/status/status.component.scss
  src/app/system/status/status.component.spec.ts
  src/app/system/status/status.component.ts
  src/app/system/users/users-list/users-list.component.spec.ts
  src/app/system/users/users.component.spec.ts
  src/app/user/account/account.component.spec.ts
  src/app/user/dashboard/dashboard.component.spec.ts
  src/app/user/membership/membership.component.spec.ts
  src/app/user/profile/profile.component.spec.ts
  src/app/user/user-form/password-form/password-form.component.spec.ts
  src/app/user/user-form/user-form.component.spec.ts
  src/app/user/user-menu/user-menu.component.spec.ts
  src/app/user/user.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.spec.ts
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/results/results.component.spec.ts
Labels: chore, testing

#342 feat(new-resource-form): make visible the required prop fields (DSP-1115)
  src/app/app.module.ts
  src/app/main/directive/invalid-control-scroll.directive.spec.ts
  src/app/main/directive/invalid-control-scroll.directive.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-project/select-project.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
Labels: enhancement

#363 feat(select-resource-class): allow accented character (DSP-1241)
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
Labels: enhancement

#364 chore: update the dsp-ui and dsp-js versions to the latest
  package-lock.json
  package.json
Labels: chore

#366 refactor(project landing page): add interfaces for metadata object (DSP-1183)
  src/app/project/board/address-template/address-template.component.ts
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.html
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.ts
  src/app/project/board/board.component.html
  src/app/project/board/board.component.ts
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.ts
  src/app/project/board/dataset-metadata.ts
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.html
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.ts
  src/app/project/board/organisation-template/organisation-template.component.ts
  src/app/project/board/person-template/person-template.component.html
  src/app/project/board/person-template/person-template.component.ts
  src/app/project/board/project-tab-view/project-tab-view.component.html
  src/app/project/board/project-tab-view/project-tab-view.component.scss
  src/app/project/board/project-tab-view/project-tab-view.component.ts
Labels: refactor

#368 feat(project landing page): add copy to clipboard functionality (DSP-1248)
  package.json
  src/app/app.module.ts
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.ts
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/board/board.component.ts
  src/app/project/board/dataset-metadata.ts
  src/app/project/board/project-tab-view/project-tab-view.component.html
Labels: enhancement, refactor

#371 refactor(app+main)!: comment out the search and everything related to resources (DSP-1291)
  README.md
  src/app/app-global.ts
  src/app/app-routing.module.ts
  src/app/main/header/header.component.html
Labels: breaking, refactor

#370 refactor!: set up the login page as a starting page (DSP-1292)
  src/app/app-routing.module.ts
  src/app/main/login/login.component.ts
Labels: breaking, refactor
