Repository dasch-swiss/dsp-das, pull requests merged in 2021-02, with the labels that each got.

#365 feat(list editor): Adds support for editing lists (DSP-741)
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.html
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.scss
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts
  src/app/project/list/list-item-form/list-item-form.component.html
  src/app/project/list/list-item-form/list-item-form.component.scss
  src/app/project/list/list-item-form/list-item-form.component.ts
  src/app/project/list/list-item/list-item.component.html
  src/app/project/list/list-item/list-item.component.ts
Labels: enhancement

#377 feat(ontology): update cardinality in resource class (DSP-1266)
  package-lock.json
  package.json
  src/app/main/dialog/dialog.component.html
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.scss
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.scss
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
  src/assets/style/_config.scss
Labels: enhancement

#380 feat(ontology): edit res class info (DSP-1209)
  package-lock.json
  src/app/main/dialog/dialog.component.html
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
Labels: enhancement

#378 feat(list-editor): add deletion functionality (DSP-1334)
  package-lock.json
  src/app/main/dialog/dialog.component.html
  src/app/project/list/list-item-form/list-item-form.component.html
  src/app/project/list/list-item-form/list-item-form.component.spec.ts
  src/app/project/list/list-item-form/list-item-form.component.ts
  src/app/project/list/list-item/list-item.component.html
  src/app/project/list/list-item/list-item.component.spec.ts
  src/app/project/list/list-item/list-item.component.ts
  src/assets/i18n/en.json
Labels: enhancement

#382 feat(ontology): default language for property label
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.scss
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
Labels: bug, enhancement

#386 feat(list-editor): delete list root node (DSP-1356)
  src/app/project/list/list.component.html
  src/app/project/list/list.component.scss
  src/app/project/list/list.component.spec.ts
  src/app/project/list/list.component.ts
Labels: enhancement

#388 feat(list-editor): reposition a child node amongst its siblings (DSP-1340)
  package-lock.json
  package.json
  src/app/project/list/list-item-form/list-item-form.component.html
  src/app/project/list/list-item-form/list-item-form.component.ts
  src/app/project/list/list-item/list-item.component.html
  src/app/project/list/list-item/list-item.component.spec.ts
  src/app/project/list/list-item/list-item.component.ts
Labels: enhancement

#389 feat(ontology): refactor list of properties in resource class (DSP-1360)
  src/app/app.module.ts
  src/app/main/cache/cache.service.ts
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.spec.ts
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.scss
  src/app/project/ontology/property-info/property-info.component.spec.ts
  src/app/project/ontology/property-info/property-info.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.scss
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
Labels: bug, enhancement

#390 fix(ontology): bug fix in list property (DSP-1368)
  src/app/project/ontology/property-info/property-info.component.spec.ts
  src/app/project/ontology/property-info/property-info.component.ts
Labels: bug

#393 refactor(tslint): use lint and refactor code (DSP-1369)
  .github/workflows/main.yml
  docs/how-to-contribute/index.md
  src/app/main/directive/base-value.directive.ts
  src/app/main/directive/invalid-control-scroll.directive.ts
  src/app/main/error/error.component.ts
  src/app/main/header/header.component.ts
  src/app/main/help/help.component.ts
  src/app/main/main.component.ts
  src/app/material-module.ts
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.ts
  src/app/project/ontology/default-data/default-resource-classes.ts
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.ts
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.ts
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/property-info/property-info.component.spec.ts
  src/app/project/ontology/property-info/property-info.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
  src/app/system/projects/projects.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
  src/app/workspace/resource/resource.component.ts
  src/tslint.json
Labels: chore

#391 feat(ontology): separate list of ontology properties (DSP-1364)
  src/app/app-routing.module.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.scss
  src/app/project/ontology/property-info/property-info.component.ts
Labels: enhancement

#396 chore(tests): script to find ignored tests
  .github/workflows/main.yml
  e2e/src/footer.e2e-spec.ts
  find-ignored-tests.sh
Labels: chore

#399 chore(gh-ci): update release please configuration (DSP-1381)
  .github/workflows/main.yml
Labels: chore

#395 feat(list-editor): insert a child node at a specific position (DSP-1301)
  package-lock.json
  package.json
  src/app/main/dialog/dialog.component.html
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.html
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts
  src/app/project/list/list-item-form/list-item-form.component.html
  src/app/project/list/list-item-form/list-item-form.component.ts
  src/app/project/list/list-item/list-item.component.html
  src/app/project/list/list-item/list-item.component.spec.ts
  src/app/project/list/list-item/list-item.component.ts
Labels: enhancement
