Repository dasch-swiss/dsp-das, pull requests merged in 2021-09, with the labels that each got.

#511 feat(config)!: update config file for better iiif support (DSP-1880)
  src/app/app-init.service.spec.ts
  src/app/app-init.service.ts
  src/app/app.module.ts
  src/app/main/declarations/dsp-iiif-config.ts
  src/app/main/services/app-init.service.ts
  src/app/workspace/resource/representation/upload/upload-file.service.spec.ts
  src/app/workspace/resource/representation/upload/upload-file.service.ts
  src/app/workspace/resource/services/geoname.service.spec.ts
  src/app/workspace/resource/services/geoname.service.ts
  src/app/workspace/resource/services/upload-file.service.spec.ts
  src/app/workspace/resource/services/upload-file.service.ts
  src/config/config.dev.json
  src/config/config.prod.json
  src/config/config.test-server.json
Labels: bug, enhancement, refactor, breaking

#515 refactor(gh-ci): split workflow tasks
  .github/release-drafter.yml
  .github/workflows/main.yml
Labels: refactor, chore

#513 fix(audio): sanitize audio url (DSP-1819)
  src/app/workspace/resource/representation/audio/audio.component.html
  src/app/workspace/resource/representation/audio/audio.component.ts
Labels: bug

#514 fix(deps): fix security vulnerability
  package-lock.json
Labels: warning, dependencies

#518 feat(resource): optimize resource instance form (DSP-1256)
  src/app/main/directive/base-value.directive.ts
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.spec.ts
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.html
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.ts
  src/app/workspace/resource/services/value-operation-event.service.ts
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
Labels: bug, enhancement, refactor

#519 refactor: remove CoreModule dependency (DSP-1884)
  src/app/app.module.ts
  src/app/main/cache/cache.service.spec.ts
  src/app/main/error/error-handler.service.spec.ts
  src/app/project/board/board.component.spec.ts
  src/app/project/collaboration/add-user/add-user.component.spec.ts
  src/app/project/collaboration/collaboration.component.spec.ts
  src/app/project/collaboration/select-group/select-group.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/list/list.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.spec.ts
  src/app/project/ontology/ontology.component.spec.ts
  src/app/project/project-form/project-form.component.spec.ts
  src/app/project/project.component.spec.ts
  src/app/system/projects/projects-list/projects-list.component.spec.ts
  src/app/system/projects/projects.component.spec.ts
  src/app/system/users/users-list/users-list.component.spec.ts
  src/app/system/users/users.component.spec.ts
  src/app/user/account/account.component.spec.ts
  src/app/user/dashboard/dashboard.component.spec.ts
  src/app/user/membership/membership.component.spec.ts
  src/app/user/profile/profile.component.spec.ts
  src/app/user/user-form/password-form/password-form.component.spec.ts
  src/app/user/user-form/user-form.component.spec.ts
  src/app/user/user-menu/user-menu.component.spec.ts
  src/app/user/user.component.spec.ts
  src/app/workspace/resource/project.service.spec.ts
  src/app/workspace/resource/resource.component.spec.ts
  src/app/workspace/results/results.component.spec.ts
  src/app/workspace/search/search-panel/search-panel.component.html
Labels: refactor

#521 chore(deps): bump dsp-js to latest version (DSP-1883)
  package-lock.json
  package.json
Labels: bug, dependencies

#520 refactor: fix style in resource, search-panel and progress-indicator (DSP-1887)
  src/app/main/action/progress-indicator/progress-indicator.component.html
  src/app/main/action/progress-indicator/progress-indicator.component.scss
  src/app/main/action/progress-indicator/progress-indicator.component.spec.ts
  src/app/main/action/progress-indicator/progress-indicator.component.ts
  src/app/workspace/resource/operations/add-value/add-value.component.html
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.scss
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
  src/assets/style/_elements.scss
  src/assets/style/_responsive.scss
  src/assets/style/_viewer.scss
  src/assets/style/main.scss
Labels: refactor, styling

#522 refactor: remove SearchModule dependency (DSP-1888)
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/main/header/header.component.spec.ts
Labels: refactor

#525 refactor: remove ViewerModule dependency (DSP-1890)
  src/app/app.module.ts
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.spec.ts
  src/app/workspace/resource/resource.component.spec.ts
  src/app/workspace/results/results.component.spec.ts
Labels: refactor

#527 chore(login): add autocomplete to login form (DSP-1892)
  src/app/main/action/login-form/login-form.component.html
  src/app/main/login/login.component.scss
Labels: chore

#526 refactor: update remaining dsp-ui imports (DSP-1891)
  package-lock.json
  package.json
  src/app/app.component.spec.ts
  src/app/main/dialog/dialog.component.ts
  src/app/main/header/header.component.ts
  src/app/main/help/help.component.spec.ts
  src/app/main/main.component.spec.ts
  src/app/project/board/board.component.spec.ts
  src/app/project/collaboration/add-user/add-user.component.spec.ts
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/project/collaboration/collaboration.component.spec.ts
  src/app/project/collaboration/select-group/select-group.component.spec.ts
  src/app/project/collaboration/select-group/select-group.component.ts
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.spec.ts
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/permission/permission.component.spec.ts
  src/app/project/project-form/project-form.component.spec.ts
  src/app/project/project-form/project-form.component.ts
  src/app/project/project.component.spec.ts
  src/app/system/groups/groups-list/groups-list.component.ts
  src/app/system/projects/projects-list/projects-list.component.spec.ts
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/projects/projects.component.spec.ts
  src/app/system/users/users-list/users-list.component.spec.ts
  src/app/system/users/users-list/users-list.component.ts
  src/app/system/users/users.component.spec.ts
  src/app/user/account/account.component.spec.ts
  src/app/user/dashboard/dashboard.component.spec.ts
  src/app/user/membership/membership.component.spec.ts
  src/app/user/membership/membership.component.ts
  src/app/user/profile/profile.component.spec.ts
  src/app/user/user-form/password-form/password-form.component.spec.ts
  src/app/user/user-form/password-form/password-form.component.ts
  src/app/user/user-form/user-form.component.spec.ts
  src/app/user/user-form/user-form.component.ts
  src/app/user/user-menu/user-menu.component.spec.ts
  src/app/user/user.component.spec.ts
  src/app/workspace/comparison/comparison.component.ts
  src/app/workspace/intermediate/intermediate.component.spec.ts
  src/app/workspace/intermediate/intermediate.component.ts
  src/app/workspace/resource/dsp-resource.ts
  src/app/workspace/resource/properties/properties.component.spec.ts
  src/app/workspace/resource/representation/file-representation.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.ts
  src/app/workspace/resource/resource.component.spec.ts
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/results/results.component.spec.ts
  src/app/workspace/results/results.component.ts
  src/styles.scss
Labels: refactor

#528 style: refactor style after moving dsp-ui to the app (DSP-1894)
  package-lock.json
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
  src/assets/style/_elements.scss
  src/assets/style/main.scss
Labels: styling, chore

#529 feat: support textarea (DSP-1896)
  package-lock.json
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/operations/display-edit/display-edit.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.ts
Labels: enhancement

#531 fix(resource-instance-form): resource class name now updates correctly (DSP-1810)
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
Labels: bug

#534 refactor: openseadragon prod build fix (DSP-1779)
  angular.json
  package-lock.json
  package.json
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/config/config.prod.json
Labels: refactor

#535 refactor(modules): clean up imports and npm packages
  package-lock.json
  src/app/app.module.ts
  src/app/material-module.ts
Labels: refactor, dependencies

#537 fix(links): trust external links (DSP-1904)
  src/app/main/directive/external-links.directive.ts
Labels: bug

#538 fix(resource): increase width of space between entries of incoming links (DSP-1908)
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.scss
  src/app/workspace/resource/properties/properties.component.ts
  src/assets/style/_elements.scss
Labels: enhancement, refactor, styling

#539 refactor(fulltext-search): persist fulltext search term in input field (DSP-1674)
  src/app/main/services/component-communication-event.service.ts
  src/app/workspace/results/list-view/list-view.component.ts
  src/app/workspace/search/fulltext-search/fulltext-search.component.ts
Labels: refactor

#540 fix(error): improve the current error handler in DSP-APP (DSP-1911)
  src/app/main/error/error-handler.service.ts
  src/app/main/services/notification.service.ts
  src/app/workspace/resource/resource.component.html
Labels: bug, enhancement, refactor

#542 fix: gravsearch results don't appear after page refresh (DSP-1675)
  src/app/workspace/results/list-view/list-view.component.spec.ts
  src/app/workspace/results/list-view/list-view.component.ts
Labels: bug
