Repository dasch-swiss/dsp-das, pull requests merged in 2021-05, with the labels that each got.

#434 feat(DMP): own resource viewer (DSP-1586)
  package-lock.json
  src/app/app.module.ts
  src/app/workspace/resource/dsp-resource.ts
  src/app/workspace/resource/incoming.service.spec.ts
  src/app/workspace/resource/incoming.service.ts
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/resource-properties/resource-properties.component.html
  src/app/workspace/resource/resource-properties/resource-properties.component.scss
  src/app/workspace/resource/resource-properties/resource-properties.component.spec.ts
  src/app/workspace/resource/resource-properties/resource-properties.component.ts
  src/app/workspace/resource/resource-toolbar/resource-toolbar.component.html
  src/app/workspace/resource/resource-toolbar/resource-toolbar.component.scss
  src/app/workspace/resource/resource-toolbar/resource-toolbar.component.spec.ts
  src/app/workspace/resource/resource-toolbar/resource-toolbar.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/assets/style/_elements.scss
Labels: enhancement

#441 refactor: Replace favicon and term Knora by DSP (DSP-1181 / DSP-1342)
  README.md
  docs/how-to-use/data.md
  docs/how-to-use/index.md
  docs/how-to-use/system.md
  e2e/src/help.e2e-spec.ts
  src/app/main/header/header.component.scss
  src/app/main/header/header.component.ts
  src/app/main/help/help.component.ts
  src/app/main/main.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.html
  src/app/system/projects/projects.component.ts
  src/app/system/users/users.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
  src/assets/images/akka-icon.svg
  src/assets/images/dasch-icon-black.svg
  src/assets/images/dasch-icon-purple.svg
  src/assets/images/dasch-icon-white.svg
  src/assets/images/knora-app-banner.svg
  src/assets/images/knora-app-icon.svg
  src/favicon.ico
Labels: refactor

#438 chore(gh-actions): automatically detect common vulnerabilities and coding errors
  .github/workflows/codeql-analysis.yml
Labels: chore

#443 chore(environment): add test-server config (DSP-1650)
  angular.json
  package.json
  src/config/config.test-server.json
  src/environments/environment.test-server.ts
Labels: chore

#440 feat(ontology): new method to change gui order (DSP-1567/DSP-1646)
  package-lock.json
  package.json
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.spec.ts
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.scss
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.scss
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.scss
  src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/app/workspace/resource/resource-properties/resource-properties.component.spec.ts
  src/app/workspace/resource/resource.component.spec.ts
  src/assets/style/_elements.scss
Labels: bug, dependencies, enhancement

#444 chore(project): resolve regex term (DSP-1654)
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/project/project-form/project-form.component.ts
Labels: chore

#451 feat(search): specify linked resource in advanced search (DSP-1661)
  package-lock.json
  package.json
Labels: dependencies, enhancement

#449 docs: update documentation about contribution (DSP-1657)
  README.md
  docs/how-to-contribute/index.md
Labels: documentation

#445 feat(resource): display region annotations in still images (DSP-1585)
  src/app/material-module.ts
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.scss
  src/app/workspace/resource/resource.component.ts
Labels: enhancement

#442 fix: disable progress bar if search results are empty (DSP-1575)
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.scss
  src/app/workspace/results/results.component.ts
Labels: bug
