Repository dasch-swiss/dsp-das, pull requests merged in 2021-06, with the labels that each got.

#455 feat(ontology): new cardinality workflow (DSP-1652)
  docs/assets/images/data-model-class-select-representation.png
  docs/assets/images/data-model-create.png
  docs/assets/images/data-model-property-create.png
  docs/assets/images/data-model-property-select-existing.png
  docs/assets/images/data-model-property-select-type.png
  docs/assets/images/project-create.png
  docs/assets/style/theme.css
  docs/how-to-use/project.md
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/ontology.service.spec.ts
  src/app/project/ontology/ontology.service.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.scss
  src/app/project/ontology/property-form/property-form.component.spec.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.scss
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.spec.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.scss
  src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.html
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.scss
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.spec.ts
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/assets/style/_elements.scss
Labels: bug, enhancement, refactor

#458 docs: prepare documentation for docs.dasch.swiss (DSP-1721)
  docs/assets/icons/dasch-icon-white.svg
  docs/assets/style/theme.css
  docs/how-to-use/project.md
  mkdocs.yml
Labels: documentation

#460 docs: fix dead links and replace screenshots in project
  docs/assets/images/dashboard.png
  docs/assets/images/data-model-add-property.png
  docs/assets/images/data-model-add-source.png
  docs/assets/images/data-model-edit-source.png
  docs/assets/images/data-model-init.png
  docs/assets/images/project-list.png
  docs/how-to-use/data.md
  docs/how-to-use/index.md
  docs/how-to-use/project.md
  docs/how-to-use/user.md
  mkdocs.yml
Labels: documentation

#461 chore(cookie-policy): reactivate the cookie policy banner (DSP-1727)
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/main/cookie-policy/cookie-policy.component.scss
  src/app/main/main.component.html
  src/app/main/main.component.scss
  src/app/main/main.component.ts
Labels: chore

#463 chore(gh-ci): update docs deployment (DSP-1741)
  .github/workflows/main.yml
Labels: bug, chore

#466 chore: empty landing page instead login (DSP-1756)
  src/app/main/main.component.scss
  src/app/main/main.component.ts
Labels: chore

#467 docs: refactor documentation and set correct links
  README.md
  docs/README.md
  docs/contribution/docs-documentation.md
  docs/contribution/index.md
  docs/contribution/release-notes.md
  docs/user-guide/data.md
  docs/user-guide/index.md
  docs/user-guide/project.md
  docs/user-guide/publication.md
  docs/user-guide/system.md
  docs/user-guide/user.md
  mkdocs.yml
  src/app/main/help/help.component.ts
Labels: documentation

#468 docs(user-guide): fix navigation links
  mkdocs.yml
Labels: documentation

#470 docs(search): add advanced search user guide (DSP-1662)
  docs/assets/images/advanced-search-linked-resource.png
  docs/assets/images/advanced-search-match.png
  docs/assets/images/advanced-search-regex.png
  docs/user-guide/data.md
Labels: documentation

#473 feat(config)!: add geoname config (DSP-1672)
  package-lock.json
  package.json
  src/config/config.dev.json
  src/config/config.prod.json
Labels: breaking, dependencies, enhancement

#472 feat(upload)!: add upload form for still images (DSP-1761)
  src/app/app.module.ts
  src/app/workspace/resource/representation/upload/upload-file.service.spec.ts
  src/app/workspace/resource/representation/upload/upload-file.service.ts
  src/app/workspace/resource/representation/upload/upload.component.html
  src/app/workspace/resource/representation/upload/upload.component.scss
  src/app/workspace/resource/representation/upload/upload.component.spec.ts
  src/app/workspace/resource/representation/upload/upload.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.scss
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
  src/app/workspace/resource/resource.component.ts
  src/config/config.dev.json
  src/config/config.prod.json
  src/config/config.test-server.json
Labels: breaking, enhancement

#476 docs(ontology): update docs and show hint in ontology-form (DSP-1139)
  docs/user-guide/project.md
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/assets/style/_elements.scss
Labels: documentation, enhancement

#475 feat(ontology): display description for default and existing props (DSP-1154)
  package-lock.json
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/property-form/property-form.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
Labels: enhancement

#477 feat(ontology): add property to res class that is in use (DSP-1631)
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.ts
  src/app/project/ontology/property-form/property-form.component.spec.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
Labels: enhancement
