Repository dasch-swiss/dsp-das, pull requests merged in 2021-03, with the labels that each got.

#397 fix(ontology): set the cache earlier in case of only one ontology (DSP-1374)
  package-lock.json
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-info/property-info.component.html
Labels: bug

#400 refactor(project landing page): use metadata endpoint to get data from backend (DSP-1199)
  src/app/project/board/address-template/address-template.component.ts
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.html
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.scss
  src/app/project/board/attribution-tab-view/attribution-tab-view.component.ts
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/board/board.component.spec.ts
  src/app/project/board/board.component.ts
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.html
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.spec.ts
  src/app/project/board/contacts-tab-view/contacts-tab-view.component.ts
  src/app/project/board/dataset-metadata.service.ts
  src/app/project/board/dataset-metadata.ts
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.html
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.spec.ts
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.ts
  src/app/project/board/organisation-template/organisation-template.component.ts
  src/app/project/board/person-template/person-template.component.html
  src/app/project/board/person-template/person-template.component.spec.ts
  src/app/project/board/person-template/person-template.component.ts
  src/app/project/board/project-tab-view/project-tab-view.component.html
  src/app/project/board/project-tab-view/project-tab-view.component.scss
  src/app/project/board/project-tab-view/project-tab-view.component.spec.ts
  src/app/project/board/project-tab-view/project-tab-view.component.ts
  src/app/project/board/terms-tab-view/terms-tab-view.component.html
  src/app/project/board/terms-tab-view/terms-tab-view.component.scss
  src/app/project/board/terms-tab-view/terms-tab-view.component.spec.ts
Labels: refactor

#404 fix(project): disable error handler in metadata request (DSP-1395)
  src/app/project/board/board.component.ts
Labels: bug

#401 refactor(ontology): improve ontology editor design (DSP-1376)
  .eslintignore
  .eslintrc.json
  src/app/app.module.ts
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/default-data/default-resource-classes.ts
  src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/property-info/property-info.component.scss
  src/app/project/ontology/property-info/property-info.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.scss
  src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
Labels: enhancement, styling

#407 refactor(project landing page): update metadata typings (DSP-1393)
  package.json
  src/app/app.module.ts
  src/app/project/board/dataset-metadata.service.ts
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.html
  src/app/project/board/dataset-tab-view/dataset-tab-view.component.ts
  src/app/project/board/organisation-template/organisation-template.component.ts
  src/app/project/board/person-template/person-template.component.html
  src/app/project/board/project-tab-view/project-tab-view.component.html
  src/app/project/board/project-tab-view/project-tab-view.component.ts
  src/app/project/board/url-template/url-template.component.ts
Labels: refactor

#410 fix(deps): package dependency build errors (DSP-1400)
  package-lock.json
  package.json
Labels: bug, dependencies

#403 refactor(list-editor): new list form refactor (DSP-1392)
  src/app/main/dialog/dialog.component.html
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.ts
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.html
  src/app/project/list/list-item-form/list-item-form.component.html
  src/app/project/list/list-item-form/list-item-form.component.ts
  src/app/project/list/list-item/list-item.component.html
  src/app/project/list/list.component.ts
Labels: refactor

#385 feat(ontology): edit data model info (DSP-1208)
  package-lock.json
  package.json
  src/app/main/dialog/dialog.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
Labels: enhancement

#411 refactor(project metadata page): enable error handler (DSP-1396)
  src/app/project/board/board.component.ts
Labels: refactor

#406 feat(ontology): form to create and edit property (DSP-1210)
  Makefile
  src/app/app.module.ts
  src/app/main/declarations/autocomplete-item.ts
  src/app/main/dialog/dialog.component.html
  src/app/project/collaboration/add-user/add-user.component.ts
  src/app/project/collaboration/select-group/select-group.component.ts
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.html
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts
  src/app/project/list/list-item-form/list-item-form.component.scss
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/default-data/default-resource-classes.ts
  src/app/project/ontology/ontology-form/ontology-form.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.scss
  src/app/project/ontology/property-form/property-form.component.spec.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.scss
  src/app/project/ontology/property-info/property-info.component.spec.ts
  src/app/project/ontology/property-info/property-info.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.spec.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.service.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.html
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.scss
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.spec.ts
  src/app/project/ontology/resource-class-property-form/resource-class-property-form.component.ts
  src/app/user/membership/membership.component.ts
  src/assets/style/_elements.scss
Labels: enhancement
