Repository dasch-swiss/dsp-das, pull requests merged in 2021-11, with the labels that each got.

#570 chore(deps): use release of ckeditor custom build (DEV-189)
  package-lock.json
  package.json
Labels: chore

#571 fix(value): display ckEditor in case of rich-text property (DEV-182)
  package-lock.json
  package.json
  src/app/main/action/confirmation-dialog/confirmation-dialog.component.scss
  src/app/main/action/confirmation-dialog/confirmation-message/confirmation-message.component.scss
  src/app/workspace/resource/operations/add-value/add-value.component.html
  src/app/workspace/resource/operations/add-value/add-value.component.scss
  src/app/workspace/resource/operations/add-value/add-value.component.ts
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/operations/display-edit/display-edit.component.scss
  src/app/workspace/resource/operations/display-edit/display-edit.component.spec.ts
  src/app/workspace/resource/operations/display-edit/display-edit.component.ts
  src/app/workspace/resource/services/value.service.ts
  src/app/workspace/resource/values/boolean-value/boolean-value.component.scss
  src/app/workspace/resource/values/color-value/color-picker/color-picker.component.scss
  src/app/workspace/resource/values/color-value/color-value.component.scss
  src/app/workspace/resource/values/date-value/date-input-text/date-edit/date-edit.component.scss
  src/app/workspace/resource/values/date-value/date-input-text/date-input-text.component.scss
  src/app/workspace/resource/values/date-value/date-input/date-input.component.scss
  src/app/workspace/resource/values/date-value/date-value.component.scss
  src/app/workspace/resource/values/decimal-value/decimal-value.component.scss
  src/app/workspace/resource/values/geoname-value/geoname-value.component.scss
  src/app/workspace/resource/values/int-value/int-value.component.scss
  src/app/workspace/resource/values/interval-value/interval-input/interval-input.component.scss
  src/app/workspace/resource/values/interval-value/interval-value.component.scss
  src/app/workspace/resource/values/link-value/link-value.component.scss
  src/app/workspace/resource/values/list-value/list-value.component.scss
  src/app/workspace/resource/values/text-value/ck-editor.ts
  src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.scss
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.scss
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.ts
  src/app/workspace/resource/values/text-value/text-value-as-xml/text-value-as-xml.component.ts
  src/app/workspace/resource/values/time-value/time-input/time-input.component.scss
  src/app/workspace/resource/values/time-value/time-value.component.scss
  src/app/workspace/resource/values/uri-value/uri-value.component.scss
  src/app/workspace/results/list-view/resource-grid/resource-grid.component.scss
  src/app/workspace/results/list-view/resource-list/resource-list.component.scss
  src/assets/style/_viewer.scss
  src/assets/style/main.scss
Labels: bug, enhancement, refactor, dependencies

#576 fix(error): resolve error handler in case of server error (DEV-205)
  src/app/main/error/error-handler.service.ts
Labels: bug

#572 refactor: move datadog rum methods to service (DEV-190)
  src/app/app-init.service.spec.ts
  src/app/app-init.service.ts
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/main/action/login-form/login-form.component.spec.ts
  src/app/main/action/login-form/login-form.component.ts
  src/app/main/services/datadog-rum.service.spec.ts
  src/app/main/services/datadog-rum.service.ts
Labels: refactor

#575 feat(resource): add additional routing for an ark url of a value (DEV-196)
  src/app/app-routing.module.ts
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/operations/display-edit/display-edit.component.spec.ts
  src/app/workspace/resource/operations/display-edit/display-edit.component.ts
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.spec.ts
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/assets/style/_viewer.scss
Labels: enhancement

#579 chore: small code improvements
  CODEOWNERS
  src/app/main/action/progress-indicator/progress-indicator.component.scss
  src/app/main/help/help.component.ts
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/search/fulltext-search/fulltext-search.component.scss
Labels: refactor

#580 feat(still-image): use the color of the color property for the line color (DEV-210)
  src/app/workspace/resource/representation/still-image/still-image.component.ts
Labels: enhancement

#581 feat(resource)!: new resource route (DEV-196)
  package-lock.json
  src/app/app-init.service.spec.ts
  src/app/app-init.service.ts
  src/app/app-routing.module.ts
  src/app/app.component.spec.ts
  src/app/main/declarations/app-config.ts
  src/app/main/declarations/dsp-app-config.ts
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.spec.ts
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.spec.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.ts
  src/app/workspace/resource/resource.component.spec.ts
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/resource/services/geoname.service.spec.ts
  src/app/workspace/resource/services/incoming.service.spec.ts
  src/app/workspace/resource/services/incoming.service.ts
  src/app/workspace/resource/services/project.service.spec.ts
  src/app/workspace/resource/services/project.service.ts
  src/app/workspace/resource/services/resource.service.spec.ts
  src/app/workspace/resource/services/resource.service.ts
  src/app/workspace/resource/values/geoname-value/geoname-value.component.spec.ts
  src/config/config.dev.json
  src/config/config.prod.json
  src/config/config.test-server.json
  test.config.ts
Labels: enhancement, refactor, breaking

#584 fix(text-value): display line breaks in read mode of paragraph text values (DEV-211)
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.ts
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
  src/assets/style/_viewer.scss
Labels: bug

#583 feat: update UI on region color change (DEV-215)
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
Labels: enhancement

#586 fix(fulltext-search): update projects list dropdown on new project creation (DEV-212)
  src/app/main/services/component-communication-event.service.ts
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/workspace/search/fulltext-search/fulltext-search.component.ts
Labels: bug

#588 chore(deps): update angular to v12
  .eslintrc.js
  README.md
  angular.json
  package-lock.json
  package.json
  src/app/main/action/confirmation-dialog/confirmation-dialog.component.spec.ts
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/property-info/property-info.component.scss
  src/app/project/ontology/resource-class-info/resource-class-info.component.scss
  src/app/workspace/resource/values/yet-another-date-value/date-picker/date-picker.component.ts
  src/assets/style/_elements.scss
  src/assets/style/_mixins.scss
  src/assets/style/_search.scss
  src/assets/style/_theme.scss
  src/assets/style/main.scss
  src/assets/style/material-theme.scss
  src/styles.scss
Labels: refactor, dependencies

#590 fix(ontology): resolve gui order issue (DEV-222)
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
Labels: bug

#591 feat(properties): ckEditor Internal Links (DEV-118)
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.html
  src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.spec.ts
  src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.ts
Labels: enhancement

#593 fix(results): display xml in a better way (DEV-96)
  src/app/workspace/results/list-view/resource-grid/resource-grid.component.html
  src/app/workspace/results/list-view/resource-list/resource-list.component.html
  src/app/workspace/results/list-view/resource-list/resource-list.component.scss
  src/assets/style/_elements.scss
Labels: enhancement

#595 fix(value): bug fix in text-value-as-string (DEV-242)
  package-lock.json
  package.json
  src/app/workspace/resource/operations/add-value/add-value.component.ts
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.ts
Labels: bug

#597 fix(projects): correctly refresh projects list when activating/deactivating projects (DEV-230)
  package-lock.json
  src/app/main/dialog/dialog.component.html
  src/app/system/projects/projects-list/projects-list.component.html
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/projects/projects.component.html
  src/app/system/projects/projects.component.ts
  src/assets/i18n/de.json
  src/assets/i18n/en.json
Labels: bug
