Repository dasch-swiss/dsp-das, pull requests merged in 2022-02, with the labels that each got.

#643 fix(ontology): support subproperty in ontology editor (DEV-332)
  package-lock.json
  package.json
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/ontology.service.spec.ts
  src/app/project/ontology/ontology.service.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/assets/style/_ontology.scss
Labels: bug, enhancement, dependencies

#644 feat!: display dsp release number (DEV-420)
  src/app/app-init.service.spec.ts
  src/app/app-init.service.ts
  src/app/main/declarations/app-config.ts
  src/app/main/declarations/dsp-config.ts
  src/app/main/footer/footer.component.html
  src/app/main/grid/grid.component.scss
  src/app/main/header/header.component.html
  src/app/main/header/header.component.scss
  src/app/main/header/header.component.spec.ts
  src/app/main/header/header.component.ts
  src/app/main/help/help.component.html
  src/app/main/help/help.component.scss
  src/app/main/help/help.component.spec.ts
  src/app/main/help/help.component.ts
  src/app/main/main.component.html
  src/assets/style/_theme.scss
  src/config/config.dev.json
  src/config/config.prod.json
  src/config/config.test-server.json
Labels: enhancement, breaking, dependencies

#650 chore(deps): update packages
  package-lock.json
  package.json
Labels: dependencies

#651 fix(main): bug fix in configuration file in case of prod mode (DEV-491)
  src/app/app-init.service.spec.ts
  src/app/app-init.service.ts
Labels: bug

#654 refactor(google fonts): self host google fonts (DEV-471)
  src/assets/fonts/material-icons/MaterialIcons-Regular.eot
  src/assets/fonts/material-icons/MaterialIcons-Regular.ttf
  src/assets/fonts/material-icons/MaterialIcons-Regular.woff
  src/assets/fonts/material-icons/MaterialIcons-Regular.woff2
  src/assets/fonts/roboto/roboto-v29-latin-300.woff2
  src/assets/fonts/roboto/roboto-v29-latin-500.woff2
  src/assets/fonts/roboto/roboto-v29-latin-700.woff2
  src/assets/fonts/roboto/roboto-v29-latin-italic.woff2
  src/assets/fonts/roboto/roboto-v29-latin-regular.woff2
  src/assets/style/_font.scss
  src/assets/style/main.scss
  src/index.html
Labels: refactor

#645 feat(add-link-resource-button): Add Link Resource Button (DEV-404)
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.ts
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.html
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.scss
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.spec.ts
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts
  src/app/workspace/resource/values/link-value/link-value.component.html
  src/app/workspace/resource/values/link-value/link-value.component.spec.ts
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: enhancement

#658 chore(open-sea-dragon): update OpenSeadragon to v3.0.0
  package-lock.json
  package.json
Labels: chore

#661 fix(ontology-editor): display sub-properties the correct way (DEV-530)
  src/app/project/ontology/ontology.service.ts
Labels: bug

#660 feat(resource): display permissions (DEV-454)
  src/app/app.module.ts
  src/app/main/declarations/admin-permissions.ts
  src/app/main/pipes/string-transformation/title-from-camel-case.pipe.spec.ts
  src/app/main/pipes/string-transformation/title-from-camel-case.pipe.ts
  src/app/material-module.ts
  src/app/system/projects/projects.component.ts
  src/app/workspace/resource/permission-info/permission-info.component.html
  src/app/workspace/resource/permission-info/permission-info.component.scss
  src/app/workspace/resource/permission-info/permission-info.component.spec.ts
  src/app/workspace/resource/permission-info/permission-info.component.ts
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.ts
  src/assets/style/_mixins.scss
  src/assets/style/main.scss
Labels: bug, enhancement, refactor

#667 fix(permission-info): better permission string handling (DEV-537)
  src/app/workspace/resource/permission-info/permission-info.component.ts
Labels: enhancement, refactor, styling

#666 fix(resource): resource viewer is broken if fileRepresentation has restricted view (DEV-455)
  src/app/workspace/resource/permission-info/permission-info.component.scss
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
Labels: bug, styling

#669 chore(rollbar): add environment to the config
  src/app/rollbar.ts
Labels: chore

#671 fix(permission-info): close permission info on scrolling (DEV-552)
  src/app/workspace/resource/permission-info/permission-info.component.html
  src/app/workspace/resource/permission-info/permission-info.component.ts
  src/app/workspace/results/results.component.html
Labels: bug

#674 feat(ontology): adjust tooltip text when property is inherited (DEV-323)
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.ts
Labels: enhancement
