Repository dasch-swiss/dsp-das, pull requests merged in 2022-01, with the labels that each got.

#626 fix(resource): bug fix in pdf viewer (DEV-338)
  package-lock.json
  package.json
  src/app/workspace/resource/representation/document/document.component.scss
Labels: bug

#630 fix(archive representation): display resource with archive representation (DEV-354)
  src/app/workspace/resource/resource.component.ts
Labels: bug

#628 refactor: clean up code after dsp-js update (DEV-282)
  package-lock.json
  package.json
  src/app/project/board/board.component.ts
Labels: refactor, dependencies

#629 refactor(ontology): clean up unused code (DEV-304)
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/main/services/datadog-rum.service.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.html
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.scss
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.spec.ts
  src/app/project/ontology/ontology-visualizer/ontology-visualizer.component.ts
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.html
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.scss
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.spec.ts
  src/app/project/ontology/ontology-visualizer/visualizer/visualizer.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.spec.ts
Labels: refactor, dependencies

#633 fix(advanced search): update comparison operators in case of rich text (DEV-326)
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/specify-property-value.component.ts
Labels: enhancement

#632 feat(resource): display deleted resource (DEV-299)
  package-lock.json
  package.json
  src/app/workspace/resource/properties/properties.component.html
  src/app/workspace/resource/properties/properties.component.scss
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-resource-class/search-select-resource-class.component.spec.ts
Labels: enhancement, dependencies

#635 fix(date-value): do not submit in case of period button (DEV-373)
  src/app/workspace/resource/values/yet-another-date-value/date-value-handler/date-value-handler.component.html
  src/app/workspace/resource/values/yet-another-date-value/date-value-handler/date-value-handler.component.ts
Labels: bug

#640 chore(angular): optimize ng s in dev mode
  angular.json
Labels: chore

#634 feat(ontology): support partOf value to create book res class (DEV-180)
  docs/assets/images/Fig42.png
  docs/user-guide/project.md
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
Labels: enhancement, dependencies

#641 fix(project): better project form validation (DEV-336)
  src/app/project/board/board.component.html
  src/app/project/project-form/project-form.component.html
  src/app/project/project-form/project-form.component.ts
Labels: bug, refactor
