Repository dasch-swiss/dsp-das, pull requests merged in 2022-06, with the labels that each got.

#758 feat(list): add support for deleting child node comments (DEV-965)
  package-lock.json
  package.json
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.spec.ts
  src/app/project/list/list-item-form/edit-list-item/edit-list-item.component.ts
Labels: enhancement

#755 feat(resource): create new resource instance directly from ontology's class (DEV-959)
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
Labels: enhancement

#762 chore: change codeowner before I leave
  CODEOWNERS
Labels: chore

#760 feat(project): proof of new project workflow concept (DEV-985)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/main/action/hint/hint.component.scss
  src/app/main/action/hint/hint.component.spec.ts
  src/app/main/action/hint/hint.component.ts
  src/app/main/status/status.component.ts
  src/app/project/beta/ontology-classes/ontology-class-instance/ontology-class-instance.component.html
  src/app/project/beta/ontology-classes/ontology-class-instance/ontology-class-instance.component.scss
  src/app/project/beta/ontology-classes/ontology-class-instance/ontology-class-instance.component.spec.ts
  src/app/project/beta/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.html
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.scss
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.spec.ts
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts
  src/app/project/beta/ontology-classes/ontology-classes.component.html
  src/app/project/beta/ontology-classes/ontology-classes.component.scss
  src/app/project/beta/ontology-classes/ontology-classes.component.spec.ts
  src/app/project/beta/ontology-classes/ontology-classes.component.ts
  src/app/project/list/list.component.html
  src/app/project/list/list.component.spec.ts
  src/app/project/list/list.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.spec.ts
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/ontology.service.spec.ts
  src/app/project/ontology/ontology.service.ts
  src/app/project/ontology/property-form/property-form.component.spec.ts
  src/app/project/ontology/property-info/property-info.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/project/project.component.spec.ts
  src/app/project/project.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/results/list-view/list-view.component.html
  src/app/workspace/results/list-view/list-view.component.scss
  src/app/workspace/results/list-view/list-view.component.spec.ts
  src/app/workspace/results/list-view/list-view.component.ts
  src/app/workspace/search/expert-search/expert-search.component.spec.ts
  src/app/workspace/search/expert-search/expert-search.component.ts
  src/assets/style/_layout.scss
Labels: enhancement

#763 refactor(link-value): List all of a superclass's subclasses (DEV-997)
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: refactor

#766 fix(link-value): list resource classes from all ontologies in project (DSP-1034)
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: bug

#765 feat(project): proof of new project workflow concept (DEV-1001)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/main/action/hint/hint.component.html
  src/app/main/dialog/dialog.component.html
  src/app/project/beta/ontology-classes/ontology-class-instance/ontology-class-instance.component.html
  src/app/project/beta/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.html
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts
  src/app/project/beta/ontology-classes/ontology-classes.component.html
  src/app/project/beta/ontology-classes/ontology-classes.component.ts
  src/app/project/beta/settings/settings.component.html
  src/app/project/beta/settings/settings.component.scss
  src/app/project/beta/settings/settings.component.spec.ts
  src/app/project/beta/settings/settings.component.ts
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/board/board.component.spec.ts
  src/app/project/board/board.component.ts
  src/app/project/collaboration/collaboration.component.spec.ts
  src/app/project/collaboration/collaboration.component.ts
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.ts
  src/app/project/list/list.component.ts
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.ts
  src/app/project/permission/permission.component.spec.ts
  src/app/project/permission/permission.component.ts
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/project/project.component.ts
  src/app/system/projects/projects-list/projects-list.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/resource/services/resource.service.ts
  src/assets/style/_layout.scss
  src/assets/style/main.scss
Labels: enhancement

#767 docs (README): Update broken links of the main README file (DEV-1045)
  README.md
Labels: documentation

#770 fix(link-value): hotfix - add onto iri to api request (DEV-1034)
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: bug

#771 fix(date-value-handler): Date value fix (DEV-392)
  angular.json
  src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.html
  src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.spec.ts
  src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.ts
Labels: bug
