Repository dasch-swiss/dsp-das, pull requests merged in 2022-04, with the labels that each got.

#695 feat(replace-file): Replace Uploaded Files (DEV-684)
  .gitignore
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.ts
  src/app/workspace/resource/representation/archive/archive.component.html
  src/app/workspace/resource/representation/archive/archive.component.ts
  src/app/workspace/resource/representation/audio/audio.component.html
  src/app/workspace/resource/representation/audio/audio.component.scss
  src/app/workspace/resource/representation/audio/audio.component.ts
  src/app/workspace/resource/representation/document/document.component.html
  src/app/workspace/resource/representation/document/document.component.ts
  src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.html
  src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.scss
  src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.spec.ts
  src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.ts
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/resource/services/value-operation-event.service.ts
Labels: enhancement

#701 fix(ontology): display all classes in a property (DEV-564)
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/ontology/property-info/property-info.component.scss
Labels: styling

#702 style(resource): display class label of incoming link (DEV-568)
  src/app/workspace/resource/properties/properties.component.html
Labels: styling

#708 feat(link-value): add progress indicator (DEV-605)
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/operations/display-edit/display-edit.component.ts
  src/app/workspace/resource/values/link-value/link-value.component.html
  src/app/workspace/resource/values/link-value/link-value.component.scss
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: enhancement

#709 fix(create-link-value): Create new resource instance to link when adding a new value (DEV-789)
  src/app/workspace/resource/operations/add-value/add-value.component.html
  src/app/workspace/resource/operations/add-value/add-value.component.ts
Labels: bug

#710 feat(link-value): enter newly created link value automatically (DEV-687)
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: enhancement

#711 fix(link-value): re-validate form on cancel (DEV-611)
  src/app/main/dialog/dialog.component.ts
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.html
  src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.ts
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: bug

#712 refactor: use constants from js-lib directly (DEV-799)
  package-lock.json
  package.json
  src/app/project/ontology/default-data/default-resource-classes.ts
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.spec.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/operator-constants.ts
Labels: refactor, dependencies

#703 fix(region): highlight info of clicked region (DEV-724)
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
  src/assets/style/_elements.scss
Labels: bug

#698 feat(representation): implement video player incl. preview (DEV-701)
  src/app/app.module.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/directive/disable-context-menu.directive.spec.ts
  src/app/main/directive/disable-context-menu.directive.ts
  src/app/main/pipes/time.pipe.spec.ts
  src/app/main/pipes/time.pipe.ts
  src/app/main/services/notification.service.ts
  src/app/workspace/resource/representation/archive/archive.component.ts
  src/app/workspace/resource/representation/audio/audio.component.ts
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.html
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.scss
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.spec.ts
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.ts
  src/app/workspace/resource/representation/document/document.component.ts
  src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/representation/video/video-preview/video-preview.component.html
  src/app/workspace/resource/representation/video/video-preview/video-preview.component.scss
  src/app/workspace/resource/representation/video/video-preview/video-preview.component.spec.ts
  src/app/workspace/resource/representation/video/video-preview/video-preview.component.ts
  src/app/workspace/resource/representation/video/video.component.html
  src/app/workspace/resource/representation/video/video.component.scss
  src/app/workspace/resource/representation/video/video.component.spec.ts
  src/app/workspace/resource/representation/video/video.component.ts
  src/app/workspace/resource/resource-link-form/resource-link-form.component.html
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/assets/images/preview-not-available.png
  src/assets/style/_elements.scss
  src/assets/style/main.scss
Labels: enhancement

#718 fix(text-value-as-string): links in text values (DEV-797)
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
Labels: bug
