Repository dasch-swiss/dsp-das, pull requests merged in 2022-03, with the labels that each got.

#677 feat(archive-value): Download archive files with original filename (DEV-295)
  src/app/workspace/resource/representation/archive/archive.component.ts
Labels: enhancement

#679 chore(deps): bump angular to version 13 (DEV-631)
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/app/main/action/confirmation-dialog/confirmation-dialog.component.spec.ts
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.scss
  src/app/project/project-form/project-form.component.html
  src/app/workspace/resource/resource-link-form/resource-link-form.component.html
  src/app/workspace/resource/values/color-value/color-picker/color-picker.component.ts
  src/app/workspace/resource/values/date-value/date-input-text/date-edit/date-edit.component.ts
  src/app/workspace/resource/values/date-value/date-input-text/date-input-text.component.ts
  src/app/workspace/resource/values/date-value/date-input/date-input.component.ts
  src/app/workspace/resource/values/interval-value/interval-input/interval-input.component.ts
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
  src/app/workspace/resource/values/time-value/time-input/time-input.component.ts
  src/app/workspace/resource/values/yet-another-date-value/date-picker/date-picker.component.ts
  src/app/workspace/resource/values/yet-another-date-value/date-value-handler/date-value-handler.component.ts
  src/assets/style/_theme.scss
  src/assets/style/material-theme.scss
  src/polyfills.ts
  src/test.ts
Labels: dependencies

#682 fix(gravsearch): fix list value restriction (DEV-486)
  src/app/workspace/search/services/gravsearch-generation.service.spec.ts
  src/app/workspace/search/services/gravsearch-generation.service.ts
Labels: bug

#683 fix(value): do not use linkify in text value as html (DEV-563)
  package-lock.json
  package.json
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/values/text-value/text-value-as-html/text-value-as-html.component.html
Labels: bug, dependencies

#673 fix(error): display 500 server error when the api is not healthy (DEV-475)
  package-lock.json
  package.json
  src/app/main/action/login-form/login-form.component.html
  src/app/main/action/login-form/login-form.component.ts
  src/app/main/dialog/dialog.component.html
  src/app/main/dialog/dialog.component.ts
  src/app/main/error/error-handler.service.spec.ts
  src/app/main/error/error-handler.service.ts
  src/app/main/error/error.component.html
  src/app/main/error/error.component.spec.ts
  src/app/main/error/error.component.ts
  src/app/main/header/header.component.ts
  src/app/main/services/session.service.ts
  src/assets/style/main.scss
  src/assets/test-data/api-error-0.json
  src/assets/test-data/api-error-500.json
  src/config/config.dev.json
Labels: bug, enhancement

#684 refactor(value): remove old date value components (DEV-633)
  src/app/app.module.ts
  src/app/project/ontology/default-data/default-properties.ts
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/project/project-form/project-form.component.html
  src/app/user/user-form/password-form/password-form.component.html
  src/app/user/user-form/user-form.component.html
  src/app/workspace/resource/operations/add-value/add-value.component.html
  src/app/workspace/resource/operations/display-edit/display-edit.component.html
  src/app/workspace/resource/resource-instance-form/select-properties/switch-properties/switch-properties.component.html
  src/app/workspace/resource/values/date-value/calendar-header/calendar-header.component.html
  src/app/workspace/resource/values/date-value/calendar-header/calendar-header.component.scss
  src/app/workspace/resource/values/date-value/calendar-header/calendar-header.component.spec.ts
  src/app/workspace/resource/values/date-value/calendar-header/calendar-header.component.ts
  src/app/workspace/resource/values/date-value/date-input-text/date-edit/date-edit.component.html
  src/app/workspace/resource/values/date-value/date-input-text/date-edit/date-edit.component.scss
  src/app/workspace/resource/values/date-value/date-input-text/date-edit/date-edit.component.spec.ts
  src/app/workspace/resource/values/date-value/date-input-text/date-edit/date-edit.component.ts
  src/app/workspace/resource/values/date-value/date-input-text/date-input-text.component.html
  src/app/workspace/resource/values/date-value/date-input-text/date-input-text.component.scss
  src/app/workspace/resource/values/date-value/date-input-text/date-input-text.component.spec.ts
  src/app/workspace/resource/values/date-value/date-input-text/date-input-text.component.ts
  src/app/workspace/resource/values/date-value/date-input/date-input.component.html
  src/app/workspace/resource/values/date-value/date-input/date-input.component.scss
  src/app/workspace/resource/values/date-value/date-input/date-input.component.spec.ts
  src/app/workspace/resource/values/date-value/date-input/date-input.component.ts
  src/app/workspace/resource/values/date-value/date-picker/date-picker.component.html
  src/app/workspace/resource/values/date-value/date-picker/date-picker.component.scss
  src/app/workspace/resource/values/date-value/date-picker/date-picker.component.spec.ts
  src/app/workspace/resource/values/date-value/date-picker/date-picker.component.ts
  src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.html
  src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.scss
  src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.spec.ts
  src/app/workspace/resource/values/date-value/date-value-handler/date-value-handler.component.ts
  src/app/workspace/resource/values/date-value/date-value.component.html
  src/app/workspace/resource/values/date-value/date-value.component.scss
  src/app/workspace/resource/values/date-value/date-value.component.spec.ts
  src/app/workspace/resource/values/date-value/date-value.component.ts
  src/app/workspace/resource/values/yet-another-date-value/yet-another-date-value.component.html
  src/app/workspace/resource/values/yet-another-date-value/yet-another-date-value.component.scss
  src/app/workspace/resource/values/yet-another-date-value/yet-another-date-value.component.spec.ts
  src/app/workspace/resource/values/yet-another-date-value/yet-another-date-value.component.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/specify-property-value/search-date-value/search-date-value.component.ts
Labels: refactor

#687 chore(deps): bump js-lib to latest (DEV-669)
  package-lock.json
  package.json
  src/app/main/error/error-handler.service.spec.ts
  src/app/main/error/error.component.spec.ts
  src/app/user/user.component.spec.ts
Labels: dependencies

#690 feat(still-image): IIIF URL copy button (DEV-524)
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/assets/style/_elements.scss
Labels: enhancement

#689 feat(still-image): new draw region icon (DEV-569)
  src/app/main/header/header.component.ts
  src/app/workspace/resource/representation/add-region-form/add-region-form.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/assets/images/draw-region-icon.svg
Labels: styling

#693 fix(help): refactor version number and fix dead link (DEV-678)
  src/app/main/help/help.component.ts
Labels: bug

#694 refactor: clean up code, tests and packages
  .github/workflows/main.yml
  package-lock.json
  src/app/main/error/error-handler.service.spec.ts
Labels: refactor, testing, dependencies

#696 fix(mkdocs): update mkdocs to 1.3.0 (DEV-736)
  docs/requirements.txt
Labels: bug
