Repository dasch-swiss/dsp-das, pull requests merged in 2022-08, with the labels that each got.

#785 feat(archive): new archive representation view (DEV-1084)
  src/app/workspace/resource/representation/archive/archive.component.html
  src/app/workspace/resource/representation/archive/archive.component.scss
  src/app/workspace/resource/representation/archive/archive.component.spec.ts
  src/app/workspace/resource/representation/video/video.component.scss
  src/assets/style/_elements.scss
Labels: enhancement

#788 fix(login-form): keep user on same page after login (DEV-1158)
  src/app/main/action/login-form/login-form.component.ts
  src/app/workspace/resource/representation/archive/archive.component.html
Labels: bug

#790 feat(projects): changes to nav bar (DEV-1101)
  src/app/main/status/status.component.spec.ts
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.html
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.scss
  src/app/project/beta/ontology-classes/ontology-class-item/ontology-class-item.component.ts
  src/app/project/beta/ontology-classes/ontology-classes.component.html
  src/app/project/collaboration/collaboration.component.spec.ts
  src/app/project/permission/permission.component.spec.ts
  src/app/project/project.component.html
  src/app/project/project.component.scss
  src/app/project/project.component.ts
  src/app/workspace/results/list-view/resource-list/resource-list.component.html
  src/app/workspace/results/list-view/resource-list/resource-list.component.ts
  src/assets/style/_layout.scss
Labels: enhancement

#794 fix(notification): Notifications only appearing for a split second (DEV-1093)
  src/app/main/services/notification.service.ts
Labels: bug

#795 Update main.yml - remove deploy-docs
  .github/workflows/main.yml
Labels: chore

#797 style(file-representations): adjust styling of file representation components (DEV-1186)
  src/app/workspace/resource/representation/archive/archive.component.html
  src/app/workspace/resource/representation/archive/archive.component.scss
  src/app/workspace/resource/representation/audio/audio.component.html
  src/app/workspace/resource/representation/audio/audio.component.scss
  src/app/workspace/resource/representation/document/document.component.html
  src/app/workspace/resource/representation/document/document.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/assets/style/_elements.scss
Labels: styling

#801 fix(list): hide title (DEV-1207)
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/project/list/list-info-form/list-info-form.component.ts
Labels: bug

#799 feat(ontology): ontology editor read mode (DEV-1183)
  src/app/project/beta/settings/settings.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-info/property-info.component.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
  src/app/project/project.component.html
Labels: enhancement

#803 chore(file-representation): add credentials to all file download requests (DEV-1257)
  src/app/workspace/resource/representation/archive/archive.component.ts
  src/app/workspace/resource/representation/audio/audio.component.html
  src/app/workspace/resource/representation/audio/audio.component.ts
  src/app/workspace/resource/representation/document/document.component.ts
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/representation/text/text.component.ts
  src/app/workspace/resource/representation/video/video.component.html
  src/app/workspace/resource/representation/video/video.component.scss
  src/app/workspace/resource/representation/video/video.component.ts
Labels: chore

#805 feat(list-value): show hierarchy of list node (DEV-1092)
  src/app/workspace/resource/values/list-value/list-value.component.html
  src/app/workspace/resource/values/list-value/list-value.component.spec.ts
  src/app/workspace/resource/values/list-value/list-value.component.ts
  src/assets/style/_viewer.scss
Labels: enhancement

#809 chore(deps): update js-lib version to 7.4.2
  package-lock.json
  package.json
  src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  src/app/workspace/resource/resource-instance-form/select-resource-class/select-resource-class.component.spec.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.spec.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-property/search-select-property.component.spec.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-resource-class/search-select-resource-class.component.spec.ts
Labels: chore, dependencies
