Repository dasch-swiss/dsp-das, pull requests merged in 2022-05, with the labels that each got.

#722 refactor: clean up jsDocs and delete deprecated methods (DEV-741)
  src/app/main/action/message/message.component.ts
  src/app/main/action/sort-button/sort-button.component.ts
  src/app/main/action/string-literal-input/string-literal-input.component.ts
  src/app/main/directive/admin-image/admin-image.config.ts
  src/app/main/directive/admin-image/admin-image.directive.ts
  src/app/main/directive/existing-name/existing-name.directive.ts
  src/app/main/header/header.component.spec.ts
  src/app/project/project-form/project-form.component.ts
  src/app/system/groups/groups-list/groups-list.component.html
  src/app/user/user-form/password-form/password-form.component.html
  src/app/user/user-form/user-form.component.html
  src/app/user/user-form/user-form.component.ts
  src/app/workspace/results/list-view/list-view.component.spec.ts
  src/app/workspace/results/list-view/list-view.component.ts
  src/app/workspace/search/advanced-search/advanced-search.component.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.ts
  src/app/workspace/search/expert-search/expert-search.component.ts
  src/app/workspace/search/fulltext-search/fulltext-search.component.ts
  src/app/workspace/search/search-panel/search-panel.component.ts
Labels: refactor

#723 style(ontology): crop loooong ontology labels (DEV-493)
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
Labels: styling

#725 feat(resource): better progress indicator handling in resource viewer (DEV-638)
  src/app/workspace/resource/representation/archive/archive.component.ts
  src/app/workspace/resource/representation/audio/audio.component.ts
  src/app/workspace/resource/representation/document/document.component.ts
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/representation/video/video.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
Labels: enhancement

#728 chore(gh): merge wrong created branch into correct one
  src/app/main/error/error.component.html
  src/app/main/error/error.component.spec.ts
  src/app/main/error/error.component.ts
  src/app/user/user-form/user-form.component.html
  src/app/user/user-form/user-form.component.spec.ts
  src/app/user/user-form/user-form.component.ts
Labels: duplicate, chore

#730 fix(representation): disable progress indicator correctly (DEV-905)
  src/app/workspace/resource/resource.component.ts
Labels: bug

#734 feat(hint): display hint about fulltext search (DEV-901)
  docs/user-guide/data.md
  src/app/app.module.ts
  src/app/main/action/hint/hint.component.html
  src/app/main/action/hint/hint.component.scss
  src/app/main/action/hint/hint.component.spec.ts
  src/app/main/action/hint/hint.component.ts
  src/app/main/grid/grid.component.scss
  src/app/workspace/results/list-view/list-view.component.html
  src/app/workspace/results/list-view/list-view.component.scss
  src/app/workspace/search/fulltext-search/fulltext-search.component.html
  src/app/workspace/search/search-panel/search-panel.component.html
  src/app/workspace/search/search-panel/search-panel.component.scss
  src/app/workspace/search/search-panel/search-panel.component.ts
  src/assets/style/_elements.scss
  src/assets/style/_responsive.scss
  src/assets/style/_search.scss
Labels: enhancement

#736 feat(link-value): Show message when no search results returned (DEV-846)
  src/app/workspace/resource/values/link-value/link-value.component.html
  src/app/workspace/resource/values/link-value/link-value.component.ts
Labels: enhancement

#733 feat(onto-editor) delete resource class and property comments (DEV-698)
  package-lock.json
  package.json
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
Labels: enhancement

#737 feat(ontology): select link class from all ontologies (DEV-688)
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/property-form/property-form.component.spec.ts
  src/app/project/ontology/property-form/property-form.component.ts
Labels: enhancement

#738 refactor(project): resolve issues in lists and with status 204
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.ts
  src/app/project/list/list.component.html
  src/app/project/list/list.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.ts
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.ts
Labels: bug, refactor

#739 feat(error): handle 504 timeout error with snackbar (DEV-751)
  src/app/main/services/error-handler.service.ts
  src/app/main/services/notification.service.ts
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/results/list-view/list-view.component.ts
  src/app/workspace/search/fulltext-search/fulltext-search.component.ts
Labels: enhancement, refactor

#740 fix(ontology): unsupported property type was displayed wrong (DEV-936)
  src/app/project/ontology/ontology.service.ts
Labels: bug

#742 feat(representation)!: new navigation in still-image viewer (DEV-895)
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/video/video.component.html
  src/app/workspace/resource/representation/video/video.component.scss
  src/assets/style/_elements.scss
Labels: enhancement, styling

#744 fix(error): resolve error handler issues (DEV-938)
  src/app/main/services/error-handler.service.ts
  src/app/main/services/notification.service.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/results/list-view/list-view.component.ts
Labels: bug

#729 feat(error): add file representation error message (DEV-791)
  src/app/main/services/datadog-rum.service.ts
  src/app/main/status/status.component.html
  src/app/main/status/status.component.scss
  src/app/main/status/status.component.ts
  src/app/project/ontology/resource-class-form/resource-class-form.component.ts
  src/app/workspace/resource/representation/archive/archive.component.html
  src/app/workspace/resource/representation/archive/archive.component.ts
  src/app/workspace/resource/representation/audio/audio.component.html
  src/app/workspace/resource/representation/audio/audio.component.ts
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.html
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.scss
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.ts
  src/app/workspace/resource/representation/document/document.component.html
  src/app/workspace/resource/representation/document/document.component.scss
  src/app/workspace/resource/representation/document/document.component.ts
  src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.ts
  src/app/workspace/resource/representation/representation.service.spec.ts
  src/app/workspace/resource/representation/representation.service.ts
  src/app/workspace/resource/representation/still-image/still-image.component.html
  src/app/workspace/resource/representation/still-image/still-image.component.scss
  src/app/workspace/resource/representation/still-image/still-image.component.spec.ts
  src/app/workspace/resource/representation/still-image/still-image.component.ts
  src/app/workspace/resource/representation/video/video.component.html
  src/app/workspace/resource/representation/video/video.component.scss
  src/app/workspace/resource/representation/video/video.component.ts
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/search/fulltext-search/fulltext-search.component.ts
  src/assets/style/_elements.scss
Labels: enhancement, styling

#741 fix(representation): resolve timeline issue when resizing window (DEV-819)
  src/app/workspace/comparison/comparison.component.html
  src/app/workspace/comparison/comparison.component.ts
  src/app/workspace/resource/representation/av-timeline/av-timeline.component.ts
  src/app/workspace/resource/representation/video/video.component.html
  src/app/workspace/resource/representation/video/video.component.ts
  src/app/workspace/resource/resource.component.html
  src/app/workspace/resource/resource.component.ts
  src/app/workspace/results/results.component.html
  src/app/workspace/results/results.component.ts
Labels: bug

#747 chore(resource): display incoming links the same way as prop values (DEV-567)
  src/app/workspace/resource/properties/properties.component.html
Labels: enhancement, chore

#746 feat(resource): open resource instances from ontology class (DEV-950)
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
  src/app/project/ontology/resource-class-info/resource-class-info.component.ts
Labels: enhancement

#748 chore(classes): sort resource classes by label (DEV-952)
  src/app/project/ontology/property-form/property-form.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.html
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.scss
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.spec.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/resource-and-property-selection.component.ts
  src/app/workspace/search/advanced-search/resource-and-property-selection/search-select-resource-class/search-select-resource-class.component.spec.ts
Labels: chore

#754 refactor(form): replace matAutosize by cdkAutosize (DEV-968)
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/property-form/property-form.component.html
  src/app/project/ontology/resource-class-form/resource-class-form.component.html
  src/app/project/project-form/project-form.component.html
  src/app/workspace/resource/resource-link-form/resource-link-form.component.html
  src/app/workspace/resource/values/boolean-value/boolean-value.component.html
  src/app/workspace/resource/values/color-value/color-value.component.html
  src/app/workspace/resource/values/date-value/date-value.component.html
  src/app/workspace/resource/values/decimal-value/decimal-value.component.html
  src/app/workspace/resource/values/geoname-value/geoname-value.component.html
  src/app/workspace/resource/values/int-value/int-value.component.html
  src/app/workspace/resource/values/interval-value/interval-value.component.html
  src/app/workspace/resource/values/link-value/link-value.component.html
  src/app/workspace/resource/values/text-value/text-value-as-string/text-value-as-string.component.html
  src/app/workspace/resource/values/text-value/text-value-as-xml/text-value-as-xml.component.html
  src/app/workspace/resource/values/uri-value/uri-value.component.html
Labels: refactor

#756 fix(ontology): check if value exists without refreshing the page (DEV-923)
  src/app/project/ontology/resource-class-info/resource-class-info.component.html
Labels: bug
