Repository dasch-swiss/dsp-das, pull requests merged in 2023-03, with the labels that each got.

#936 chore(deps): update js-lib to version 8.1.0
  package-lock.json
  package.json
Labels: chore, dependencies

#946 style(document): fix pdf viewer css (DEV-1821)
  src/app/workspace/resource/representation/document/document.component.scss
Labels: bug

#947 fix(document): fix PDF viewer zoom out issue (DEV-1855)
  src/app/workspace/resource/representation/document/document.component.html
  src/app/workspace/resource/representation/document/document.component.ts
Labels: bug

#928 feat: project description (DEV-1452)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/project/board/board.component.html
  src/app/project/board/board.component.scss
  src/app/project/board/board.component.ts
  src/app/project/description/description.component.html
  src/app/project/description/description.component.scss
  src/app/project/description/description.component.spec.ts
  src/app/project/description/description.component.ts
  src/app/project/project-form/project-form.component.html
  src/app/project/project.component.html
Labels: enhancement

#958 style: add default background color to release badge (DEV-1918)
  src/app/app-init.service.ts
  src/assets/style/_theme.scss
Labels: styling, chore

#950 chore: remove beta toggle (DEV-1449)
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/main/action/login-form/login-form.component.ts
  src/app/project/collaboration/collaboration.component.spec.ts
  src/app/project/collaboration/collaboration.component.ts
  src/app/project/data-models/data-models.component.spec.ts
  src/app/project/data-models/data-models.component.ts
  src/app/project/description/description.component.html
  src/app/project/description/description.component.spec.ts
  src/app/project/description/description.component.ts
  src/app/project/list/list-info-form/list-info-form.component.html
  src/app/project/list/list-info-form/list-info-form.component.spec.ts
  src/app/project/list/list-info-form/list-info-form.component.ts
  src/app/project/list/list.component.html
  src/app/project/list/list.component.spec.ts
  src/app/project/list/list.component.ts
  src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.html
  src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.scss
  src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.spec.ts
  src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts
  src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.html
  src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.scss
  src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.spec.ts
  src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.ts
  src/app/project/ontology-classes/ontology-classes.component.html
  src/app/project/ontology-classes/ontology-classes.component.scss
  src/app/project/ontology-classes/ontology-classes.component.spec.ts
  src/app/project/ontology-classes/ontology-classes.component.ts
  src/app/project/ontology/ontology-form/ontology-form.component.html
  src/app/project/ontology/ontology-form/ontology-form.component.ts
  src/app/project/ontology/ontology.component.html
  src/app/project/ontology/ontology.component.scss
  src/app/project/ontology/ontology.component.spec.ts
  src/app/project/ontology/ontology.component.ts
  src/app/project/ontology/property-info/property-info.component.html
  src/app/project/permission/permission.component.spec.ts
  src/app/project/permission/permission.component.ts
  src/app/project/project-form/project-form.component.ts
  src/app/project/project.component.html
  src/app/project/project.component.spec.ts
  src/app/project/project.component.ts
  src/app/project/settings/settings.component.html
  src/app/project/settings/settings.component.scss
  src/app/project/settings/settings.component.spec.ts
  src/app/project/settings/settings.component.ts
  src/app/system/project-tile/project-tile.component.html
  src/app/system/project-tile/project-tile.component.ts
  src/app/system/projects/projects-list/projects-list.component.ts
  src/app/system/users/users-list/users-list.component.spec.ts
  src/app/system/users/users-list/users-list.component.ts
  src/app/user/dashboard/dashboard.component.html
  src/app/user/dashboard/dashboard.component.scss
  src/app/user/dashboard/dashboard.component.spec.ts
  src/app/user/dashboard/dashboard.component.ts
  src/app/workspace/resource/properties/properties.component.ts
  src/app/workspace/resource/resource-instance-form/resource-instance-form.component.ts
  src/app/workspace/results/list-view/list-view.component.html
  src/app/workspace/results/list-view/list-view.component.scss
  src/app/workspace/results/list-view/list-view.component.ts
  src/assets/style/main.scss
Labels: chore

#971 docs: Update documentation to include the data browser
  docs/assets/images/compare-resource-select.png
  docs/assets/images/compare-resource-view.png
  docs/assets/images/controlled-voca-create-form.png
  docs/assets/images/controlled-voca-create.png
  docs/assets/images/create-data-model.png
  docs/assets/images/create-new-resource-form-step1.png
  docs/assets/images/create-new-resource-form-step2.png
  docs/assets/images/create-new-resource-instance.png
  docs/assets/images/dashboard.png
  docs/assets/images/data-model-create2.png
  docs/assets/images/data-model-list-browser.png
  docs/assets/images/image-restricted-view-notif.png
  docs/assets/images/new-resource-form.png
  docs/assets/images/project-create-new.png
  docs/assets/images/project-settings.png
  docs/assets/images/project-workspace.png
  docs/assets/images/resource-view-with-image.png
  docs/assets/images/search-results-list.png
  docs/assets/images/system-user-menu.png
  docs/user-guide/data/search-results.md
  docs/user-guide/data/start.md
  docs/user-guide/data/work-on-data.md
  docs/user-guide/project.md
Labels: documentation

#974 docs: Add the operator "not exists"
  docs/user-guide/data/search.md
Labels: documentation

#975 fix: login button remains after sys admin login
  apps/dsp-app/src/app/main/action/login-form/login-form.component.ts
  apps/dsp-app/src/app/user/user-menu/user-menu.component.ts
Labels: bug

#977 style: fix overview page bottom padding
  apps/dsp-app/src/app/user/overview/overview.component.scss
Labels: styling

#979 chore: bump js-lib to 8.2.0
  apps/dsp-app/src/app/workspace/resource/resource-instance-form/select-project/select-project.component.spec.ts
  package-lock.json
  package.json
Labels: chore, dependencies
