Repository dasch-swiss/dsp-das, pull requests merged in 2023-04, with the labels that each got.

#982 style: overview component bottom padding
  apps/dsp-app/src/app/user/overview/overview.component.scss
Labels: styling

#985 style(header): adjust logo
  apps/dsp-app/src/app/main/header/header.component.html
  apps/dsp-app/src/app/main/header/header.component.scss
  apps/dsp-app/src/app/main/header/header.component.spec.ts
Labels: styling

#984 fix: handle 400 error during fulltext search
  apps/dsp-app/src/app/workspace/results/list-view/list-view.component.html
  apps/dsp-app/src/app/workspace/results/list-view/list-view.component.ts
  package.json
Labels: bug

#993 chore: angular mdc migration - chips
  apps/dateAdapter/src/styles.scss
  apps/dsp-app/src/app/main/dialog/dialog.component.spec.ts
  apps/dsp-app/src/app/material-module.ts
  apps/dsp-app/src/app/project/collaboration/collaboration.component.spec.ts
  apps/dsp-app/src/app/project/description/description.component.html
  apps/dsp-app/src/app/project/description/description.component.spec.ts
  apps/dsp-app/src/app/project/project-form/project-form.component.html
  apps/dsp-app/src/app/project/project-form/project-form.component.spec.ts
  apps/dsp-app/src/app/project/project-form/project-form.component.ts
  apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.html
  apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.spec.ts
  apps/dsp-app/src/app/system/projects/projects.component.spec.ts
  apps/dsp-app/src/app/system/users/users-list/users-list.component.html
  apps/dsp-app/src/app/system/users/users-list/users-list.component.spec.ts
  apps/dsp-app/src/app/system/users/users.component.spec.ts
  apps/dsp-app/src/app/user/membership/membership.component.html
  apps/dsp-app/src/app/user/overview/overview.component.spec.ts
  apps/dsp-app/src/app/user/user-form/password-form/password-form.component.html
  apps/dsp-app/src/app/user/user.component.spec.ts
  apps/dsp-app/src/app/workspace/resource/properties/properties.component.html
  apps/dsp-app/src/app/workspace/resource/representation/upload/upload.component.html
  apps/dsp-app/src/app/workspace/resource/representation/video/video.component.html
  apps/dsp-app/src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  apps/dsp-app/src/assets/style/_elements.scss
  apps/dsp-app/src/assets/style/_layout.scss
Labels: refactor, chore

#994 chore: angular mdc migration - card
  apps/dsp-app/src/app/material-module.ts
  apps/dsp-app/src/app/project/ontology/ontology.component.spec.ts
  apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-info.component.html
  apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-info.component.scss
  apps/dsp-app/src/app/project/ontology/resource-class-info/resource-class-info.component.spec.ts
  apps/dsp-app/src/app/system/projects/projects-list/projects-list.component.html
  apps/dsp-app/src/app/system/users/users-list/users-list.component.html
  apps/dsp-app/src/app/user/membership/membership.component.html
  apps/dsp-app/src/app/user/user-form/password-form/password-form.component.html
  apps/dsp-app/src/app/workspace/resource/properties/properties.component.html
  apps/dsp-app/src/app/workspace/resource/resource-instance-form/select-properties/select-properties.component.html
  apps/dsp-app/src/assets/style/_elements.scss
  apps/dsp-app/src/assets/style/_layout.scss
  apps/dsp-app/src/assets/style/main.scss
Labels: refactor, chore

#1014 fix: app breaks when on /account route
  apps/dsp-app/src/app/user/account/account.component.ts
  apps/dsp-app/src/app/user/profile/profile.component.ts
  apps/dsp-app/src/app/user/user-form/password-form/password-form.component.html
  apps/dsp-app/src/app/user/user-form/password-form/password-form.component.scss
  apps/dsp-app/src/app/user/user-form/password-form/password-form.component.spec.ts
  apps/dsp-app/src/app/user/user-form/password-form/password-form.component.ts
  apps/dsp-app/src/app/user/user-form/user-form.component.ts
Labels: bug

#1015 chore(fulltext-search): filter out deactivated projects and system projects
  apps/dsp-app/src/app/workspace/search/fulltext-search/fulltext-search.component.html
  apps/dsp-app/src/app/workspace/search/fulltext-search/fulltext-search.component.spec.ts
  apps/dsp-app/src/app/workspace/search/fulltext-search/fulltext-search.component.ts
Labels: chore

#1016 fix: unauthorized users can access the create resource form
  apps/dsp-app/src/app/project/ontology-classes/ontology-class-instance/ontology-class-instance.component.ts
Labels: bug

#1022 chore: adjust linter rules for dsp-app
  apps/dsp-app/.eslintrc.json
  apps/dsp-app/src/app/main/directive/external-links.directive.ts
  apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.spec.ts
  apps/dsp-app/src/app/project/ontology-classes/ontology-classes.component.spec.ts
  apps/dsp-app/src/app/workspace/resource/operations/create-link-resource/create-link-resource.component.spec.ts
  apps/dsp-app/src/app/workspace/resource/operations/display-edit/display-edit.component.spec.ts
  apps/dsp-app/src/app/workspace/resource/representation/replace-file-form/replace-file-form.component.spec.ts
  apps/dsp-app/src/app/workspace/resource/resource-instance-form/resource-instance-form.component.spec.ts
  apps/dsp-app/src/app/workspace/resource/values/text-value/text-value-as-xml/text-value-as-xml.component.spec.ts
Labels: chore

#998 fix(sidenav): set background color for selected list-item
  apps/dsp-app/src/app/main/services/component-communication-event.service.ts
  apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.html
  apps/dsp-app/src/app/project/ontology-classes/ontology-class-item/ontology-class-item.component.ts
  apps/dsp-app/src/app/project/project.component.html
  apps/dsp-app/src/app/project/project.component.scss
  apps/dsp-app/src/app/project/project.component.ts
  apps/dsp-app/src/index.html
Labels: bug
